/** Real page controls on the isolated candidate; no business writes are submitted. */
import { chromium } from 'playwright';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { projectId, localize } from './localize.mjs';
const origin='http://localhost:3001',doc='a0fb9f3a-4421-4af0-a018-82074e21aff8';
const authState=process.env.DOCUMENTATION_SCRATCH_AUTH ?? '/tmp/min664-reader-auth-owner.json';
const locales=process.env.CAPTURE_LOCALES?.split(',') ?? ['en','fr','de','es','it','pt-BR'];
const registry='content/documentation/reviews/scratch-page-controls-2026-10-08.json';
let records=[];try{records=JSON.parse(await readFile(registry,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}
const sourceCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
for(const locale of locales){
 const m=JSON.parse(await readFile(`messages/${locale}.json`,'utf8'));
 const browser=await chromium.launch(),context=await browser.newContext({storageState:authState,viewport:{width:1440,height:900},deviceScaleFactor:2,locale:{en:'en-US',fr:'fr-FR',de:'de-DE',es:'es-ES',it:'it-IT','pt-BR':'pt-BR'}[locale],colorScheme:'light',reducedMotion:'reduce'});await context.addCookies([{name:'NEXT_LOCALE',value:locale,url:origin}]);
 await context.addInitScript(()=>{localStorage.setItem('mangue-ui-theme','light');localStorage.setItem('cookie_consent','declined');document.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('style');s.textContent='nextjs-portal{display:none!important}*,*::before,*::after{animation:none!important;transition:none!important}';document.head.appendChild(s);});});
 const adaptations=[],blocked=[];
 await context.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());if(url.origin!==origin)throw new Error('Unexpected origin');if(request.method()!=='GET'){if(url.pathname.startsWith('/api/me/app-tabs'))return route.fallback();blocked.push({method:request.method(),path:url.pathname});return route.abort();}if(!url.pathname.startsWith(`/api/projects/${projectId}`))return route.fallback();const response=await route.fetch().catch(()=>null);if(!response)return;if(!response.ok())return route.fulfill({response});const value=await response.json(),translated=localize(value,locale);if(JSON.stringify(value)!==JSON.stringify(translated))adaptations.push(url.pathname);return route.fulfill({response,json:translated});});
 const page=await context.newPage();page.setDefaultTimeout(20000);
 async function capture(screen,target){await page.mouse.move(8,8);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(450);let b=await target.boundingBox();if(screen==='page-file-states'){b=await target.evaluate(el=>{const r=el.getBoundingClientRect(),bs=[...el.querySelectorAll('.tiptap,textarea')].map(x=>x.getBoundingClientRect());return{x:r.x,y:r.y,width:r.width,height:Math.max(...bs.map(b=>b.bottom))-r.y+16};});}if(screen==='page-history-preview'){b=await target.evaluate(el=>{const r=el.getBoundingClientRect(),ol=el.querySelector('ol');const summary=ol?.nextElementSibling;const bottom=summary?.getBoundingClientRect().bottom??ol.getBoundingClientRect().bottom;return{x:r.x,y:r.y,width:r.width,height:bottom-r.y+20};});}if(!b)throw new Error('Missing target');const v=page.viewportSize(),x=Math.max(0,Math.floor(b.x-12)),y=Math.max(0,Math.floor(b.y-12)),clip={x,y,width:Math.min(v.width-x,Math.ceil(b.width+24)),height:Math.min(v.height-y,Math.ceil(b.height+24))};const src=`/documentation/${locale}/${screen}.png`;await mkdir(`public/documentation/${locale}`,{recursive:true});await page.screenshot({path:'public'+src,clip,animations:'disabled'});records=records.filter(r=>r.locale!==locale||r.screen!==screen);records.push({locale,screen,src,sourceCommit,candidateVersion:'0.11.1',workingTreeChanges:true,runtime:'Isolated restored backend',projectId,pageId:doc,date:'2026-10-08',theme:'light',browserViewport:[v.width,v.height],viewport:[clip.width,clip.height],language:await page.locator('html').getAttribute('lang'),displayAdaptation:[...new Set(adaptations)],blockedWrites:[...blocked],submitted:false,reviewed:false,limitation:'Actual saved demo file states and historical snapshots; menu drafts do not save or restore content.'});await writeFile(registry,JSON.stringify(records,null,2)+'\n');console.log(locale+'/'+screen);}
 try{
  await page.goto(`${origin}/projects/${projectId}/pages/${doc}`,{waitUntil:'load'});await page.locator('main textarea').waitFor();await page.getByRole('link',{name:m.Pages.fileDownload,exact:true}).waitFor();await capture('page-file-states',page.locator('main'));
  await page.getByRole('button',{name:m.PageDatabase.create,exact:true}).click();await page.getByRole('menuitem',{name:m.Pages.newPage,exact:true}).waitFor();await capture('page-create-menu',page.getByRole('menu'));await page.keyboard.press('Escape');
  const editor=page.locator('main .tiptap[contenteditable=true]');await editor.press('ControlOrMeta+End');await editor.press('Enter');await page.keyboard.type('/');await page.getByText(m.Pages.blockFile,{exact:true}).waitFor();await capture('page-block-menu',page.locator('[data-page-slash-menu] [data-floating-surface]'));await page.keyboard.press('Escape');await editor.press('Backspace');
  await page.getByRole('button',{name:new RegExp('^'+m.Pages.historyTabVersions)}).first().click();await page.getByRole('tab',{name:m.Pages.historyTabVersions,exact:true}).click();const dialog=page.getByRole('dialog');await dialog.locator('ol button').first().waitFor();await dialog.locator('ol button').first().click();await dialog.getByRole('button',{name:m.Pages.historyRestore,exact:true}).waitFor();await capture('page-history-preview',dialog);
 }catch(error){console.log(locale+' failed '+error.message);console.log(await page.locator('main').innerText());records.push({locale,error:error.message.split('\n')[0],reviewed:false});await writeFile(registry,JSON.stringify(records,null,2)+'\n');}finally{await browser.close();}
}
