/** Capture the actual isolated incoming issue without accepting or rejecting it. */
import {chromium} from 'playwright';
import {writeFile,mkdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
const origin='http://localhost:3001',project='3bdf5b04-ed54-40cd-b65f-10086fed72c1';
const fixture={en:['Review an incoming keyboard report','Demonstration incoming report. Verify the described focus issue before accepting it.'],fr:['Examiner un signalement reçu concernant le clavier','Signalement de démonstration. Vérifier le problème de focus décrit avant de l’accepter.'],de:['Eingegangenen Tastaturbericht prüfen','Demobericht. Das beschriebene Fokusproblem vor dem Akzeptieren prüfen.'],es:['Revisar un informe recibido sobre el teclado','Informe de demostración. Comprueba el problema de foco descrito antes de aceptarlo.'],it:['Esaminare una segnalazione ricevuta sulla tastiera','Segnalazione dimostrativa. Verifica il problema di focus descritto prima di accettarla.'],'pt-BR':['Analisar um relato recebido sobre o teclado','Relato de demonstração. Verifique o problema de foco descrito antes de aceitá-lo.']};
function translate(v,m){if(typeof v==='string')return m[v]??v;if(Array.isArray(v))return v.map(x=>translate(x,m));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,translate(x,m)]));return v;}
const records=[],sourceCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
for(const locale of Object.keys(fixture)){
 const browser=await chromium.launch(),context=await browser.newContext({storageState:'/tmp/min664-reader-auth-owner.json',viewport:{width:1280,height:900},deviceScaleFactor:2,colorScheme:'light',locale:locale==='en'?'en-US':locale});await context.addCookies([{name:'NEXT_LOCALE',value:locale,url:origin}]);await context.addInitScript(()=>{localStorage.setItem('mangue-ui-theme','light');document.addEventListener('DOMContentLoaded',()=>{const s=document.createElement('style');s.textContent='nextjs-portal{display:none!important}';document.head.appendChild(s);});});const page=await context.newPage(),changed=[],blocked=[];page.setDefaultTimeout(20000);const mapping=Object.fromEntries(fixture.en.map((v,i)=>[v,fixture[locale][i]]));
 try{await context.route('**/api/**',async route=>{const r=route.request(),url=new URL(r.url());if(url.origin!==origin)throw new Error('Unexpected origin');if(r.method()!=='GET'){if(url.pathname.startsWith('/api/me/app-tabs'))return route.fallback();blocked.push({method:r.method(),path:url.pathname});return route.abort();}if(!url.pathname.startsWith(`/api/projects/${project}`))return route.fallback();const res=await route.fetch().catch(()=>null);if(!res)return;if(!res.ok())return route.fulfill({response:res});const body=await res.json(),value=translate(body,mapping);if(JSON.stringify(body)!==JSON.stringify(value))changed.push(url.pathname);return route.fulfill({response:res,json:value});});await page.goto(`${origin}/projects/${project}/triage`,{waitUntil:'load'});await page.getByText(fixture[locale][0],{exact:true}).first().waitFor();await page.waitForTimeout(600);await page.mouse.move(8,8);await page.evaluate(()=>document.fonts.ready);const main=page.locator('main'),b=await main.boundingBox();const src=`/documentation/${locale}/triage-incoming.png`;await mkdir(`public/documentation/${locale}`,{recursive:true});await main.screenshot({path:'public'+src,animations:'disabled'});records.push({locale,screen:'triage-incoming',src,sourceCommit,candidateVersion:'0.11.1',workingTreeChanges:true,projectId:project,issueId:'305a5c13-b838-4ad1-a0df-793ab3e159a9',date:'2026-10-08',theme:'light',browserViewport:[1280,900],viewport:[Math.round(b.width),Math.round(b.height)],language:await page.locator('html').getAttribute('lang'),displayAdaptation:changed,blockedWrites:blocked,submitted:false,reviewed:false,limitation:'Actual stored incoming demo issue. No accept, decline or duplicate action submitted.'});console.log(locale+'/triage');}catch(e){console.log(locale+' failed '+e.message.split('\n')[0]);records.push({locale,error:e.message.split('\n')[0],reviewed:false});}finally{await browser.close();await writeFile('content/documentation/reviews/scratch-triage-controls-2026-10-08.json',JSON.stringify({fixture,records},null,2)+'\n');}
}
