"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useFormatter, useNow, useTranslations } from "next-intl";
import {
  Badge,
  Button,
  Checkbox,
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
  Skeleton,
  Spinner,
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
  Textarea,
  cn,
  toast,
} from "mangue-ui";
import {
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ExternalLink,
  GitPullRequest,
  GitPullRequestDraft,
  Link2,
  MessageSquare,
  MoreHorizontal,
  Pencil,
  Reply,
  RotateCcw,
  X,
} from "lucide-react";
import { Github, Gitlab } from "@/components/git/provider-icons";
import Link from "next/link";
import { AppContentHeader } from "@/components/app-content-header";
import { BotBadge, GitLogin } from "@/components/git/git-login";
import { Markdown } from "@/components/markdown";
import { TAB_LIST_DENSE, TAB_TRIGGER_DENSE } from "@/components/tab-bar";
import { NumoIcon } from "@/components/numo-icon";
import { ProjectOrb } from "@/components/project-orb";
import { projectOrbSeed } from "@/lib/project-orb-colors";
import { PrCommits } from "@/components/pull-requests/pr-commits";
import { PrCommentComposer } from "@/components/pull-requests/pr-comment-composer";
import { PrDiff } from "@/components/pull-requests/pr-diff";
import { PrLinkIssue } from "@/components/pull-requests/pr-link-issue";
import {
  CommentReactionChips,
  ReactionPicker,
  reactionToggler,
  useCommentReactions,
  type CommentReactions,
} from "@/components/pull-requests/pr-review-comments";
import {
  PrReviewCard,
} from "@/components/pull-requests/pr-review-thread";
import { PrTimelineReview, PrTimelineRow } from "@/components/pull-requests/pr-timeline";
import { PrStateBadge } from "@/components/pull-requests/pr-state-badge";
import { PrReadinessBadge, PrReadinessControl } from "@/components/pull-requests/pr-readiness";
import { PrViewerCallout } from "@/components/pull-requests/pr-viewer-callout";
import { FormDialog } from "@/components/form-dialog";
import { useIsSendShortcut } from "@/lib/keyboard/use-send-mode";
import { UserAvatar } from "@/components/user-avatar";
import { ModelCombobox } from "@/components/agent/model-combobox";
import {
  EnvironmentCombobox,
  LOCAL_REPO_ERROR_KEYS,
  type AgentEnvironment,
} from "@/components/agent/environment-combobox";
import { ReasoningCombobox } from "@/components/agent/reasoning-combobox";
import { useLocalRepo } from "@/lib/use-local-repo";
import {
  useAgentModelsQuery,
  useReasoningLevelsFor,
} from "@/lib/use-agent-models-query";
import { useAgentPreferencesQuery } from "@/lib/use-agent-preferences-query";
import { nearestReasoningLevel, type ReasoningLevel } from "@/lib/agent-reasoning";
import {
  usePullRequestQuery,
  usePrCommentsQuery,
  usePrCommitsQuery,
  usePrReviewCommentsQuery,
} from "@/lib/use-agent-runs";
import {
  actOnPullRequestApi,
  maintainPullRequestApi,
  postPullRequestCommentApi,
  prEndpoint,
  requestPullRequestAiReviewApi,
  submitPullRequestReviewApi,
  type ChecksSummary,
  type CheckState,
  type MergeMethod,
  type PullRequestComment,
  type PullRequestCommit,
  type PullRequestListItem,
  type PullRequestReviewComment,
  type ReviewVerdict,
} from "@/lib/agent-api";
import {
  blockerFallbackUrl,
  type ReadinessAction,
  type ReadinessBlocker,
} from "@/lib/pr-readiness";
import { normalizeForgeInstant } from "@/lib/forge-time";
import { REPO_PROVIDERS } from "@/lib/repo-providers";
import { PrEndpointProvider } from "@/lib/pr-endpoint-context";
import { issueIdentifier } from "@/lib/issue-constants";
import { usePrReviewSession } from "@/lib/use-pr-review-session";
import { usePrLive } from "@/lib/use-pr-live";
import { useScrollFade } from "@/lib/use-scroll-fade";
import { PR_BODY_COMMENT_ID } from "@/lib/pr-review-reactions";
import { LocalIssueRunConfirmation } from "@/components/agent/local-issue-run-confirmation";
import {
  groupTimelineCommits,
  groupTimelineReviews,
  resolveCommitActors,
  sortTimelineOlderFirst,
  type PrTimelineEvent,
} from "@/lib/pr-timeline";
import type { MessageKey } from "@/lib/i18n-keys";
import { parseForgeLogin, prIdentifier, type RepoProviderId } from "@/lib/repo-providers";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

/**
 * PR detail panel (MIN-66 + MIN-138 + MIN-143): header (ticket +
 * status + actions), CI checks banner, then two GitHub-style tabs — the thread
 * conversation (PR description + comments) and modified files.
 * Everything is controlled by `item.prId`: since MIN-143 the PR no longer belongs to the run
 * who opened it, and a human PR has none.
 *
 * A run still controls the “Generated by Numo” badge. All provider actions remain
 * available without a run: review, comments, closing, readiness, and merge.
 * “Fix feedback” may start from the current PR head even when Numo did not create it.
 */

/** Status badge of a check. `pending` pulse: this is the only state that moves. */
function CheckDot({ state, className }: { state: CheckState; className?: string }) {
  return (
    <span
      className={cn(
        "size-2 shrink-0 rounded-full",
        state === "success" && "bg-emerald-500",
        state === "failure" && "bg-destructive",
        state === "pending" && "animate-pulse bg-amber-500",
        state === "neutral" && "bg-muted-foreground/50",
        className,
      )}
    />
  );
}

/**
 * Logo of the integration that produced the check — GitHub serves the REAL logo of
 * each App (Vercel, Socket Security, GitHub Actions, etc.), this is what we display
 * rather than a generic icon. Fallback is the icon of the forge: at GitLab
 * the CI is GitLab, and there is no other logo to show.
 *
 * Neutral background behind the image: many of these logos are transparent and
 * monochrome — without it, a black logo disappears in a dark theme.
 */
function CheckLogo({ url, provider }: { url: string | null; provider: RepoProviderId }) {
  if (url) {
    return (
      // eslint-disable-next-line @next/next/no-img-element
      <img
        src={url}
        alt=""
        className="size-5 shrink-0 rounded-[4px] bg-muted object-cover"
      />
    );
  }
  const Icon = provider === "gitlab" ? Gitlab : Github;
  return (
    <Icon className="size-5 shrink-0 rounded-[4px] bg-muted p-0.5 text-muted-foreground" />
  );
}

/** “42 s”, “3 min 7 s”. `null` when the forge does not date the check. */
function checkDuration(
  t: ReturnType<typeof useTranslations<"PullRequests">>,
  durationMs: number | null,
): string | null {
  if (durationMs == null || !Number.isFinite(durationMs) || durationMs < 0) return null;
  const seconds = Math.round(durationMs / 1000);
  return seconds < 60
    ? t("checkDurationSeconds", { seconds })
    : t("checkDurationMinutes", {
        minutes: Math.floor(seconds / 60),
        seconds: seconds % 60,
      });
}

/** The word of the state, for the checks of which the forge says nothing more. */
const CHECK_STATE_KEY: Record<CheckState, MessageKey<"PullRequests">> = {
  success: "checkStateSuccess",
  failure: "checkStateFailure",
  pending: "checkStatePending",
  neutral: "checkStateNeutral",
};

/**
 * CI check strip. Folded it fits in one line (“3/4 successful”); unfolded
 * it lists each check as GitHub does: the integration logo, the name
 * of the check, what the forge says about the result, its duration, and the link to the forge.
 *
 * Three different “no checks”, and they don’t say the same:
 * `error` = we could not read (permission of the GitHub App not accepted by
 * installation), `total === 0` = this repository has no CI, and the normal case.
 */
function ChecksBanner({
  checks,
  error,
  provider,
  loading,
}: {
  checks: ChecksSummary | null;
  error: "forbidden" | "unknown" | null;
  provider: RepoProviderId;
  loading: boolean;
}) {
  const t = useTranslations("PullRequests");
  const [open, setOpen] = useState(false);
  const now = useNow({ updateInterval: 1_000 });

  if (loading) return <p className="text-xs text-muted-foreground">{t("checksLoading")}</p>;
  if (error) {
    return (
      <p className="text-xs text-muted-foreground">
        {t(error === "forbidden" ? "checksForbidden" : "checksUnknown")}
      </p>
    );
  }
  if (!checks) return <p className="text-xs text-muted-foreground">{t("checksUnknown")}</p>;
  if (checks.total === 0) {
    return <p className="text-xs text-muted-foreground">{t("checksNone")}</p>;
  }

  const label =
    checks.state === "failure"
      ? t("checksFailing", { passing: checks.passing, total: checks.total })
      : checks.state === "pending"
        ? t("checksPending", { passing: checks.passing, total: checks.total })
        : t("checksPassing", { total: checks.total });
  const totalDuration = checks.startedAt
    ? checkDuration(
        t,
        Math.max(
          0,
          (checks.completedAt ? Date.parse(checks.completedAt) : now.getTime()) -
            Date.parse(checks.startedAt),
        ),
      )
    : null;

  return (
    <div data-testid="pr-checks" className="rounded-lg border border-border bg-card">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center gap-2 px-3.5 py-2.5 text-left outline-none"
      >
        <CheckDot state={checks.state ?? "neutral"} />
        <span className="text-sm font-medium">{label}</span>
        {totalDuration ? (
          <span className="ml-auto text-xs tabular-nums text-muted-foreground">{totalDuration}</span>
        ) : null}
        {open ? <ChevronDown className="size-4 text-muted-foreground" /> : <ChevronRight className="size-4 text-muted-foreground" />}
      </button>
      {open ? (
        <ul className="flex flex-col divide-y divide-border border-t border-border">
          {checks.checks.map((c) => {
            const duration = checkDuration(
              t,
              c.state === "pending" && c.startedAt
                ? Math.max(0, now.getTime() - Date.parse(c.startedAt))
                : c.durationMs,
            );
            // What the forge says about the result, otherwise the status word: “Failed”
            // only a second empty line under the name remains more useful.
            const detail = [c.appName, c.description ?? t(CHECK_STATE_KEY[c.state])]
              .filter(Boolean)
              .join(" · ");
            return (
              <li
                key={c.name}
                data-testid="pr-check"
                data-required={c.required == null ? "unknown" : String(c.required)}
                className="flex items-center gap-2.5 px-3.5 py-2.5"
              >
                <CheckDot state={c.state} />
                <CheckLogo url={c.appAvatarUrl} provider={provider} />
                <div className="min-w-0 flex-1">
                  <p className="flex min-w-0 items-center gap-1.5 text-sm">
                    <span className="truncate">{c.name}</span>
                    {c.required !== false ? (
                      <Badge
                        data-testid="pr-check-requirement"
                        variant="secondary"
                        className="h-4 shrink-0 px-1.5 text-[9px]"
                      >
                        {t(
                          c.required === true
                            ? "checkRequired"
                            : "checkRequirednessUnknown",
                        )}
                      </Badge>
                    ) : null}
                  </p>
                  <p className="truncate text-xs text-muted-foreground">{detail}</p>
                </div>
                {duration ? (
                  <span className="shrink-0 text-xs tabular-nums text-muted-foreground">
                    {duration}
                  </span>
                ) : null}
                {c.url ? (
                  <a
                    href={c.url}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex shrink-0 items-center gap-1 text-xs text-brand hover:underline"
                  >
                    {t("checkDetails")}
                    <ExternalLink className="size-3" />
                  </a>
                ) : null}
              </li>
            );
          })}
        </ul>
      ) : null}
    </div>
  );
}

/**
 * An entry from the conversation thread, messages AND activity combined (MIN-159).
 * The thread is ONE chronological sequence, like on GitHub: a comment, a
 * review, a push and a title change are read in the order in which they were
 * took place, not in three separate lists.
 */
type FeedEntry =
  | { key: string; id: string; createdAt: string | null; kind: "comment"; comment: PullRequestComment }
  | { key: string; id: string; createdAt: string | null; kind: "event"; event: PrTimelineEvent }
  | {
      key: string;
      id: string;
      createdAt: string | null;
      kind: "review";
      event: PrTimelineEvent;
      comments: PullRequestReviewComment[];
    };

/**
 * Messages + activity, merged and put back in order.
 *
 * Four rules carry the entire result:
 * - a commit is signed by its forge ACCOUNT, not by the written `user.name`
 * inside (`resolveCommitActors`): the timeline only knows the second, and
 * the list of commits — already loaded for its tab — is the first one;
 * - CONSECUTIVE commits fold into a single “pushed N commits”
 * (`groupTimelineCommits`), otherwise a PR of twenty commits would drown out the
 *    trois messages qui comptent ;
 * - reviews without a body by the same author fold in the same way
 * (`groupTimelineReviews`): at GitHub, a single point IS a review,
 * and a pass from Numo drops a dozen in a row;
 * - a review becomes a MAP as soon as it has something to say — a body,
 * or points placed on the code. A bare approval remains a line: it
 * has no content, and giving it an empty card would be lying about its weight.
 */
function buildFeed(
  comments: PullRequestComment[],
  timeline: PrTimelineEvent[],
  reviewComments: PullRequestReviewComment[],
  commits: PullRequestCommit[],
): FeedEntry[] {
  const commentsByReview = new Map<number, PullRequestReviewComment[]>();
  for (const comment of reviewComments) {
    if (comment.review_id == null) continue;
    const list = commentsByReview.get(comment.review_id);
    if (list) list.push(comment);
    else commentsByReview.set(comment.review_id, [comment]);
  }

  const entries: FeedEntry[] = comments.map((comment) => ({
    key: `comment:${comment.id}`,
    id: `comment:${comment.id}`,
    createdAt: comment.created_at,
    kind: "comment",
    comment,
  }));

  // Order matters: counts first, otherwise grouping commits
  // would compare git names where two pushes from the same account should meet
  // recognize.
  const events = groupTimelineReviews(
    groupTimelineCommits(resolveCommitActors(timeline, commits)),
  );
  for (const event of events) {
    if (event.kind === "reviewed") {
      const own = (event.reviewIds ?? []).flatMap((id) => commentsByReview.get(id) ?? []);
      if (event.body || own.length > 0) {
        entries.push({
          key: event.id,
          id: event.id,
          createdAt: event.createdAt,
          kind: "review",
          event,
          comments: own,
        });
        continue;
      }
    }
    entries.push({ key: event.id, id: event.id, createdAt: event.createdAt, kind: "event", event });
  }

  return sortTimelineOlderFirst(entries);
}

/**
 * A thread entry: avatar, author, time, markdown body, reactions. Serves
 * as much to the description of the PR (the comment which OPENS the thread) as to the
 * comments that follow — on the GitHub side it's the same thing, and the thread doesn't read
 * like a thread only if its first message has the same shape as the others.
 *
 * This equality also applies to reactions (MIN-147): `commentId` is worth
 * `PR_BODY_COMMENT_ID` for the description, what the server translates into the
 * subject that every forge is waiting for. Reacting therefore works EVERYWHERE in PR — the thread
 * like the diff — instead of just comments anchored to a line of code.
 */
function ThreadComment({
  commentId,
  user,
  createdAt,
  body,
  onQuoteReply,
  quotingNumo,
  reactions,
  activity,
}: {
  commentId: number;
  user: { login: string; avatar_url: string | null } | null;
  createdAt: string | null;
  body: string;
  /** Absent when there is no composition where to cite: to cite without power
      answering leads nowhere (MIN-144). */
  onQuoteReply?: () => void;
  /** This message is from Numo: quote RAPPELLE (MIN-162), and the gesture is called
      otherwise — “Reply with quote” does not say it will re-roll a pass. */
  quotingNumo?: boolean;
  /** Absent when the forge has not been able to read them: nothing is then displayed. */
  reactions?: CommentReactions;
  /** Unrolled folded ABOVE the body, for the message which carries one — the
      Numo's review is the only case: his verdict is the message, his work
      is what produced it. */
  activity?: React.ReactNode;
}) {
  const t = useTranslations("PullRequests");
  const format = useFormatter();
  const now = useNow();
  const list = reactions?.byComment.get(commentId) ?? [];

  return (
    <li className="group/comment flex flex-col gap-1.5 rounded-lg border border-border bg-card px-3.5 py-3">
      <div className="flex items-center gap-2">
        <UserAvatar
          url={user?.avatar_url}
          seed={user?.login ?? "?"}
          className="size-5"
        />
        <GitLogin
          login={user?.login}
          className="text-sm font-medium text-foreground"
        />
        {normalizeForgeInstant(createdAt, now) ? (
          <span className="shrink-0 text-xs text-muted-foreground/80">
            {format.relativeTime(normalizeForgeInstant(createdAt, now) as Date, now)}
          </span>
        ) : null}
        <span className="min-w-0 flex-1" />
        {/* The fallback of the header, for a message WITHOUT reaction: as soon as it
            wears one, the palette moves down into the reaction band, with the
            emoji she adds. Here it is revealed on hover, as
            “Quote” to the right — a permanent palette under each message
            would make a checkerboard of buttons. Returned anyway (and not mounted on
            hover) to remain accessible on the keyboard. */}
        {reactions?.canReact && list.length === 0 ? (
          <ReactionPicker
            className="-my-1 opacity-0 transition-opacity group-hover/comment:opacity-100 focus-visible:opacity-100"
            onPick={reactionToggler(reactions, commentId, list)}
          />
        ) : null}
        {onQuoteReply ? (
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon-sm"
                aria-label={t(quotingNumo ? "quoteReplyNumo" : "quoteReply")}
                className="-my-1 size-7 rounded-full text-muted-foreground opacity-0 transition-opacity group-hover/comment:opacity-100 focus-visible:opacity-100"
                onClick={onQuoteReply}
              >
                <Reply className="size-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent side="top">
              {t(quotingNumo ? "quoteReplyNumo" : "quoteReply")}
            </TooltipContent>
          </Tooltip>
        ) : null}
      </div>
      {/* The scroll is placed at a distance from the header: stuck to the name, it read
          as a second signature line. */}
      {activity ? <div className="pt-1.5">{activity}</div> : null}
      <Markdown className="text-foreground [&_code]:bg-primary/10 [&_code]:text-primary [&_pre_code]:text-inherit">
        {body}
      </Markdown>
      {reactions && list.length > 0 ? (
        <CommentReactionChips commentId={commentId} reactions={reactions} list={list} />
      ) : null}
    </li>
  );
}

export function PrDetail({
  item,
  onBack,
  onRefetchList,
  onOptimisticStateChange,
  onStateChange,
  onOpenIssue,
}: {
  item: PullRequestListItem;
  onBack: () => void;
  onRefetchList: () => void;
  /** Patches the sidebar upon clicking and renders a restoration if the forge refuses. */
  onOptimisticStateChange: (
    prId: string,
    state: PullRequestListItem["pr_state"],
  ) => () => void;
  /** Aligns the local cache to the state actually returned by the forge. */
  onStateChange: (prId: string, state: PullRequestListItem["pr_state"]) => void;
  /** Opens the linked issue in the side panel, above the page (no navigation). */
  onOpenIssue: (issueId: string, projectId: string) => void;
}) {
  const t = useTranslations("PullRequests");
  const tAgent = useTranslations("Agent");
  const isSend = useIsSendShortcut();
  const format = useFormatter();
  const {
    defaultModel: providerDefaultModel,
    cloudExecutionConfigured,
    executionBackend,
  } = useAgentModelsQuery();
  const { cloudExecutionConfigured: reviewExecutionConfigured } =
    useAgentModelsQuery("review");
  const { defaultModel, defaultReasoningLevel } = useAgentPreferencesQuery();

  const {
    pr,
    files,
    checks,
    checksError,
    viewer,
    readiness,
    loading,
    refetch: refetchPr,
  } = usePullRequestQuery(item.prId, true);
  const {
    comments,
    timeline,
    reactions: commentReactions,
    loading: commentsLoading,
    refetch: refetchComments,
  } = usePrCommentsQuery(item.prId);
  const {
    commits,
    truncated: commitsTruncated,
    loading: commitsLoading,
    refetch: refetchCommits,
  } = usePrCommitsQuery(item.prId);
  const {
    comments: reviewComments,
    threads: reviewThreads,
    reactions: reviewReactions,
    refetch: refetchReviewComments,
  } = usePrReviewCommentsQuery(prEndpoint(item.prId));
  const refreshReviewState = useCallback(async () => {
    await Promise.all([refetchReviewComments(), refetchPr()]);
  }, [refetchPr, refetchReviewComments]);
  // Live from THIS PR (MIN-161): the server pushes “this part has moved”
  // on `pull-request:{id}`, and these four caches will reread. This is what makes
  // such as a comment posted on github.com, a pushed commit, an approval or
  // a resolved wire reaches the open panel without reloading.
  usePrLive(item.prId);

  const [acting, setActing] = useState<
    null | "merge" | "close" | "reopen" | "ready_for_review" | "convert_to_draft"
  >(null);
  const [maintenanceAction, setMaintenanceAction] = useState<ReadinessAction | null>(null);
  const [editingTitle, setEditingTitle] = useState(false);
  const [titleDraft, setTitleDraft] = useState("");
  // The merge is confirmed WITH its method: bring it to the confirmation state
  // prevents a click on “merge anyway” from falling back to the default squash.
  const [confirmAction, setConfirmAction] = useState<
    null | { kind: "merge"; method?: MergeMethod } | { kind: "close" }
  >(null);
  const [reviewVerdict, setReviewVerdict] = useState<ReviewVerdict | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [reviewMessage, setReviewMessage] = useState("");
  const [relaunch, setRelaunch] = useState(true);
  /**
   * The two modes of “requesting changes” (the dialogue makes them
   * tabs, and only this request has two):
   * · `write` — we write the instruction. It serves as a VERDICT on the forge and as a
   * quick to Numo: it is the historic gesture;
   * · `findings` — we don't write it, we ask Numo to take the
   * remarks ALREADY left on the PR. Nothing is published in the name
   * of the person: the text is an instruction, not a review.
   */
  const [reviewMode, setReviewMode] = useState<"write" | "findings">("write");
  // Model of the run to launch — empty = account default (MIN-68: restart Numo
  // is a cold launch, so it has its own choice of model).
  const [model, setModel] = useState("");
  const [reasoningOverride, setReasoningOverride] = useState<ReasoningLevel | null>(null);
  const [environment, setEnvironment] = useState<AgentEnvironment>("cloud");
  const [commentBody, setCommentBody] = useState("");
  const [posting, setPosting] = useState(false);
  // Numo rereads the PR (MIN-141): a SESSION, not a blocking call — it is
  // plays IN the thread, in place of its future verdict message, and survives a
  // rechargement.
  const reviewSession = usePrReviewSession(item.prId);
  const [aiReviewDialog, setAiReviewDialog] = useState(false);
  const [aiReviewModel, setAiReviewModel] = useState("");
  const [aiReviewReasoningOverride, setAiReviewReasoningOverride] =
    useState<ReasoningLevel | null>(null);
  const [startingAiReview, setStartingAiReview] = useState(false);
  const [tab, setTab] = useState<"activity" | "commits" | "files">("activity");
  // Soft fade up and down the feed — the same as the agent conversation and
  // than the columns of the board: it only lights up on the side where there REMAINS some
  // something to see, what a fixed border cannot say.
  const feedFade = useScrollFade<HTMLDivElement>();
  // “Cite” written in the draft from outside the composer: this
  // counter tells him to go take the cursor again.
  const [quoteFocus, setQuoteFocus] = useState(0);
  // The message this draft responds to, with the quote it inserted —
  // it is she who certifies, when sent, that we always respond to this message.

  const isWorking = !!item.activeRunId;
  // The environment only makes sense for a classic agent restart. A
  // PR rereading (`pullRequestId`) voluntarily remains in the cloud: the
  // Content can come from a fork and should never become a local shell.
  const localRepo = useLocalRepo(item.project?.id ?? null);
  useEffect(() => {
    setEnvironment(localRepo.ready ? "local" : "cloud");
  }, [localRepo.ready]);

  const effectiveModel = model || defaultModel || providerDefaultModel;
  const reasoningLevels = useReasoningLevelsFor(effectiveModel);
  const reasoningLevel = nearestReasoningLevel(
    reasoningOverride ?? defaultReasoningLevel,
    reasoningLevels,
  );
  const aiReviewEffectiveModel = aiReviewModel || reviewSession.model?.instance;
  const aiReviewReasoningLevels = useReasoningLevelsFor(aiReviewEffectiveModel, "review");
  const aiReviewReasoningLevel = nearestReasoningLevel(
    aiReviewReasoningOverride ?? defaultReasoningLevel,
    aiReviewReasoningLevels,
  );
  // What THIS git account can do on this repository (MIN-144). A human gesture leaves
  // of the person's account: without account, or without right, the affordance
  // DISAPPEARS — it’s the banner that explains, once, at the top.
  const canWrite = viewer?.capability === "write";
  const canComment = canWrite || viewer?.capability === "read";
  // React to thread (MIN-147): same hook, same chips, same palette as the diff —
  // only the road changes. `canComment` (therefore `read`) is enough: the withdrawal rereads
  // the reactions of the message with this token, like the review side.
  const threadReactions = useCommentReactions(
    prEndpoint(item.prId),
    refetchComments,
    commentReactions,
    !!canComment,
    "conversation",
  );
  // “And restart Numo” only exists if a run already carries this PR: it is
  // ITS runs the new comes into branch (MIN-143). A human RA does not
  // nothing to inherit.
  //
  // The TICKET does not fall into this condition (MIN-292). He was there, and he
  // closed the gesture on the PRs opened by a NOTEBOOK session — that is to say
  // on PRs from Numo, with their branch and their runs, to which the screen responded
  // “Numo never worked on this pull request.” The lineage of a RA without
  // ticket, it is the PR itself: the server reads it by its number.
  const canRelaunch =
    item.pr_state !== "merged" &&
    item.pr_state !== "closed" &&
    !!pr?.head &&
    !!item.project &&
    reviewExecutionConfigured;
  // `item` comes from the list (DB value, possibly late by a webhook),
  // `pr` of the forge's GET (the truth): the forge wins as soon as it responds.
  const isDraft = pr?.draft ?? item.pr_state === "draft";
  const isTerminal = item.pr_state === "merged" || item.pr_state === "closed";
  const badgeState = isDraft && !isTerminal ? "draft" : item.pr_state;
  // Closed is not over: the two forges reopen, and a PR closed by
  // error was only caught on github.com (MIN-164). Merged, in
  // However, is definitive - the forge refuses, and there is nothing to offer.
  const canReopen = canWrite && item.pr_state === "closed";
  // When Numo finishes (the active run disappears from the list), refresh diff +
  // comments. Line comments are one of them: Numo can have
  // answered, and a new push changes the rows they anchor to. THE
  // commits too: this is the only time when the list changes before your eyes.
  const prevWorking = useRef(isWorking);
  useEffect(() => {
    if (prevWorking.current && !isWorking) {
      void refetchPr();
      void refetchComments();
      void refetchCommits();
      void refetchReviewComments();
    }
    prevWorking.current = isWorking;
  }, [isWorking, refetchPr, refetchComments, refetchCommits, refetchReviewComments]);

  const aiReviewActive = reviewSession.active;

  // When the pass ends, what she wrote is ON PR: the summary
  // in the thread, points in the Files tab. The two surfaces
  // refresh, like after the end of a run.
  const prevReviewing = useRef(aiReviewActive);
  useEffect(() => {
    if (prevReviewing.current && !aiReviewActive) {
      void refetchComments();
      void refetchReviewComments();
    }
    prevReviewing.current = aiReviewActive;
  }, [aiReviewActive, refetchComments, refetchReviewComments]);

  // Has Numo ever proofread EXACTLY this diff? As long as the head hasn't moved,
  // rerolling would repay a pattern turn for the same code. Unknown head (the
  // forge has not yet responded) = we're not stopping anything: it's better to leave
  // restart than block on ignorance.
  const currentHeadSha = pr?.headSha ?? null;
  const reviewUpToDate =
    !!currentHeadSha && reviewSession.reviewedHeadSha === currentHeadSha;

  // Four labels for ONE gesture (have Numo proofread): they say where
  // is the pass. The same text serves the three affordances of the same gesture —
  // the Review menu entry, the fallback button without git account, and the entry of the
  // “…” menu of the mobile —, hence the extraction: they must never say
  // different things.
  const aiReviewLabel = aiReviewActive
    ? t("numoReviewRunning")
    : reviewUpToDate
      ? t("numoReviewUpToDateShort")
      : reviewSession.run
        ? t("numoReviewRerun")
        : t("aiReview");

  /**
   * The proofreading session card, or nothing: it is there as soon as a
   * session exists on this PR, and it REMAINS there once completed (MIN-168).
   *
   * Before, it disappeared when the verdict message arrived — it was not used
   * than to hold the place of this message. Now it leads elsewhere: to
   * session that produced the review, and the conversation that we can continue there.
   * Erasing it would remove the only gateway to what has happened.
   * actually happened.
   */
  const reviewCard = reviewSession.run;

  const act = async (
    action: "merge" | "close" | "reopen" | "ready_for_review" | "convert_to_draft",
    method?: MergeMethod,
  ) => {
    if (acting) return;
    const optimisticState =
      action === "merge"
        ? "merged"
        : action === "close"
          ? "closed"
          : action === "ready_for_review"
            ? "open"
            : action === "convert_to_draft"
              ? "draft"
            : pr?.draft
              ? "draft"
              : "open";
    const rollback = onOptimisticStateChange(item.prId, optimisticState);
    setActing(action);
    setConfirmAction(null);
    try {
      const result = await actOnPullRequestApi(item.prId, action, method);
      onStateChange(item.prId, result.pr_state);
      toast.success(
        action === "merge"
          ? t("mergedToast")
          : action === "close"
            ? t("closedToast")
            : action === "reopen"
              ? t("reopenedToast")
              : action === "convert_to_draft"
                ? t("convertedToDraftToast")
                : t("readyForReviewToast"),
      );
      onRefetchList();
      await refetchPr();
    } catch (err) {
      rollback();
      onRefetchList();
      toast.error((err as Error).message);
    } finally {
      setActing(null);
    }
  };

  const handleReadinessAction = async (blocker: ReadinessBlocker) => {
    if (maintenanceAction) return;
    if (blocker.action === "mark_ready") {
      await act("ready_for_review");
      return;
    }
    if (blocker.action === "approve") {
      openReview("approve");
      return;
    }
    if (blocker.action === "resolve_conversations") {
      setTab("activity");
      return;
    }
    setMaintenanceAction(blocker.action);
    try {
      if (blocker.action === "update_branch") {
        await maintainPullRequestApi(item.prId, "update_branch");
        toast.success(t("branchUpdatedToast"));
      } else if (blocker.action === "rerun_checks") {
        const check = checks?.checks.find(
          (candidate) => candidate.state === "failure" && candidate.rerunRef,
        );
        if (!check?.rerunRef) return;
        await maintainPullRequestApi(item.prId, "rerun_check", { rerunRef: check.rerunRef });
        toast.success(t("checksRerunToast"));
      } else if (blocker.action === "enable_auto_merge") {
        await maintainPullRequestApi(item.prId, "enable_auto_merge");
      }
      await refetchPr();
    } catch (error) {
      toast.error((error as Error).message);
    } finally {
      setMaintenanceAction(null);
    }
  };

  const saveTitle = async () => {
    const title = titleDraft.trim();
    if (!title || maintenanceAction) return;
    setMaintenanceAction("open_forge");
    try {
      await maintainPullRequestApi(item.prId, "update_title", { title });
      toast.success(t("prTitleUpdatedToast"));
      setEditingTitle(false);
      onRefetchList();
      await refetchPr();
    } catch (error) {
      toast.error((error as Error).message);
    } finally {
      setMaintenanceAction(null);
    }
  };

  const canActOnBlocker = (blocker: ReadinessBlocker): boolean => {
    if (blocker.action === "mark_ready" || blocker.action === "update_branch") return canWrite;
    if (blocker.action === "approve") return canComment;
    if (blocker.action === "resolve_conversations") return canWrite;
    if (blocker.action === "rerun_checks") {
      return !!canWrite && !!checks?.checks.some((check) => check.state === "failure" && check.rerunRef);
    }
    if (blocker.action === "enable_auto_merge") return !!canWrite;
    return false;
  };

  const openReview = (verdict: ReviewVerdict) => {
    setReviewVerdict(verdict);
    setReviewMessage("");
    setReviewMode("write");
    setModel("");
    setReasoningOverride(null);
    // Relaunch only makes sense when there is a request for change, and that is its
    // expected behavior: automatically checked.
    setRelaunch(verdict === "request_changes" && canRelaunch);
  };

  /**
   * Mode toggle. The “correct remarks” prompt is PRE-WRITTEN but
   * remains editable: it is a starting point, not a form. We don't crush it
   * that if the person has not written anything else — retracing their steps should not
   * erase its prompt.
   */
  const switchReviewMode = (next: "write" | "findings") => {
    setReviewMode(next);
    if (next === "findings") {
      // Correcting the remarks necessarily means making Numo work.
      setRelaunch(true);
      if (!reviewMessage.trim()) setReviewMessage(t("reviewFindingsPrompt"));
    } else if (reviewMessage.trim() === t("reviewFindingsPrompt")) {
      setReviewMessage("");
    }
  };

  // “Correct remarks” mode: no verdict, therefore no git identity
  // required — this is what makes the button usable without a connected account. In
  // “write” mode, the verdict only goes out if you have an account to sign it.
  const postVerdict = reviewMode === "write" && !!canComment;
  // Relaunch is the only possible effect when no verdict is issued: without
  // for her, the gesture would do nothing at all.
  const relaunching = canRelaunch && (reviewMode === "findings" || relaunch) && !item.busyRunId;
  // Neither verdict to publish, nor Numo to launch: the button has NOTHING to do (no
  // git account, and a PR that Numo never touched — or works
  // Already). We deactivate it rather than letting go of a request that the
  // serveur refusera en `noEffect`.
  const reviewHasNoEffect =
    reviewVerdict === "request_changes" && !postVerdict && !relaunching;
  const relaunchUsesLocal = environment !== "cloud" && localRepo.ready;
  const relaunchBackendUnavailable =
    relaunching && !relaunchUsesLocal && !cloudExecutionConfigured;
  // What prevents the review from leaving, and its wording: the button on the foot of
  // dialog and the shortcut ⌘/Ctrl+Enter of the field read both — otherwise the
  // button would send what the button refuses.
  const reviewSubmitDisabled =
    submitting ||
    reviewHasNoEffect ||
    relaunchBackendUnavailable ||
    (!reviewMessage.trim() && reviewVerdict !== "approve");
  const reviewSubmitLabel =
    reviewMode === "findings"
      ? t("reviewFixSubmit")
      : reviewVerdict === "request_changes" && relaunching
        ? t("sendToNumo")
        : t("reviewSubmit");

  const [confirmLocalRelaunch, setConfirmLocalRelaunch] = useState(false);

  const submitReview = async (localIssueContextConfirmed = false) => {
    if (!reviewVerdict || submitting || reviewHasNoEffect) return;
    if (relaunchBackendUnavailable) {
      toast.error(tAgent("errorExecutionBackendUnavailable"));
      return;
    }
    if (relaunching && relaunchUsesLocal && !localIssueContextConfirmed) {
      setConfirmLocalRelaunch(true);
      return;
    }
    const message = reviewMessage.trim();
    // Approving without a word is legitimate; comment or request changes
    // without saying anything is not (and both providers reject an empty body).
    if (!message && reviewVerdict !== "approve") return;
    setSubmitting(true);
    try {
      const result = await submitPullRequestReviewApi(item.prId, {
        verdict: reviewVerdict,
        message,
        relaunch: relaunching && reviewVerdict === "request_changes",
        postVerdict,
        model: model || undefined,
        reasoningLevel: relaunching ? reasoningLevel : undefined,
        localExec: relaunching && relaunchUsesLocal,
        localWorktree: relaunching && environment === "worktree" && localRepo.ready,
        localIssueContextConfirmed,
      });
      // Three outcomes, three messages: the verdict has passed, the forge has folded it
      // in comments (an App cannot approve its own PR — say so,
      // rather than suggesting a green pellet), or there was none
      // not to give and it's Numo who goes to work.
      toast.success(
        result.published === "none"
          ? t("sendToNumo")
          : result.published === "comment"
            ? t("selfReviewBlocked")
            : t("reviewSubmittedToast"),
      );
      setReviewVerdict(null);
      setReviewMessage("");
      onRefetchList(); // brings up a possible new active run → polling the list.
      await Promise.all([refetchComments(), refetchPr()]);
    } catch (err) {
      toast.error((err as Error).message);
    } finally {
      setSubmitting(false);
    }
  };

  /**
   * “Have it verified by Numo” (MIN-141) — available on ANY PR, including
   * those that Numo has not opened: re-reading only requires a diff, where
   * "relaunch Numo" needs a branch to inherit from.
   *
   * The gesture passes through a dialogue because it now carries a CHOICE: the
   * model. A big PR doesn't read like a one-liner, and it's at the moment
   * of the click as we know — not in a setting set once and for all.
   */
  const openAiReviewDialog = () => {
    if (!reviewExecutionConfigured) {
      toast.error(tAgent("errorExecutionBackendUnavailable"));
      return;
    }
    // The last choice of the account, otherwise “minddy’s default” (empty string).
    setAiReviewModel(reviewSession.model?.preferred ?? "");
    setAiReviewReasoningOverride(null);
    setAiReviewDialog(true);
  };

  /**
   * Throws the pass and opens the backboard. The answer does not wait for him: it makes
   * the session, and this is the panel that shows the rest live.
   */
  const startAiReview = async () => {
    if (startingAiReview) return;
    setStartingAiReview(true);
    try {
      await requestPullRequestAiReviewApi(
        item.prId,
        aiReviewModel,
        aiReviewReasoningLevel,
      );
      setAiReviewDialog(false);
      // The pass is seen in the line: bring it back, otherwise it is played under a
      // tab that nobody looks at.
      setTab("activity");
      await reviewSession.refetch();
    } catch (err) {
      toast.error((err as Error).message);
    } finally {
      setStartingAiReview(false);
    }
  };

  // The PR thread is FLAT on the GitHub side (endpoint issues/{n}/comments: none
  // in_reply_to — only review comments anchored to the code are threaded).
  // “Reply” therefore quotes the message in the bottom composer, as does the
  // “Quote reply” from GitHub, and mentions its author to keep the thread readable.
  /**
   * Is this message from NUMO? (MIN-162)
   *
   * Two benchmarks, and the second catches up with what the first doesn't see:
   * · the account under which he writes at the forge (`viewer.numoLogin`) —
   * complete, but GitHub only: on the GitLab side it has no identity of its own
   * (MIN-146), his gestures start from the account of who linked the deposit — and a
   * Numo's message then reads as a message from that person.
   */
  const isNumoComment = (login?: string | null): boolean =>
    !!viewer?.numoLogin && login === viewer.numoLogin;

  /**
   * “Quote” — and, on a message from Numo, **reply to him**.
   *
   * Quoting someone mentions it, to keep the thread readable: that's what
   * made the GitHub “Quote reply”. On a message from Numo, mention his
   * bot account wouldn't lead anywhere — a `@minddy-app[bot]` won't wake you up
   * person. It is `@Numo` that we ask: the mention that minddy treats herself,
   * the one who restarts the pass. Responding to Numo is therefore reminding him, without
   * having to know that you have to write it down.
   *
   * The quote is enough to say what we are responding to: since MIN-168, rereading is
   * a SESSION that reads the entire thread (and keeps its own in context) — the id of the
   * quoted message, which the old pass received separately, no longer taught anything.
   */
  const quoteReply = (body: string, login?: string | null) => {
    const quoted = body
      .trim()
      .split("\n")
      .map((line) => `> ${line}`)
      .join("\n");
    const numo = isNumoComment(login);
    const mention = numo ? "@Numo " : login ? `@${login} ` : "";
    setCommentBody((d) => `${d.trim() ? `${d.trimEnd()}\n\n` : ""}${quoted}\n\n${mention}`);
    // The composer is no longer a `<textarea>` but a field with mentions (MIN-162):
    // the cursor does not land on `setSelectionRange` but on this signal, which
    // the field reads AFTER resting its contents.
    setQuoteFocus((n) => n + 1);
  };

  const submitComment = async () => {
    const body = commentBody.trim();
    if (!body || posting) return;
    setPosting(true);
    try {
      const { review } = await postPullRequestCommentApi(item.prId, body);
      setCommentBody("");
      await refetchComments();
      // The message MENTIONED Numo: his pass is already open on the server side
      // (MIN-162). We'll get her right away — that's what makes
      // appear the living card in place of the future verdict, instead of
      // leave a minute of silence during which nothing says but the gesture
      // worked.
      if (review) await reviewSession.refetch();
    } catch (err) {
      toast.error((err as Error).message);
    } finally {
      setPosting(false);
    }
  };

  // The name of this page is the PR ID — not the ticket ID, which
  // is only one relation and can be read to its right. `pr_url` comes from the list,
  // `pr.url` of the forge: the identifier IS the link to the forge, which
  // replaces the “PR #30 ↗” which was lying under the title.
  const identifier = prIdentifier(item.provider, item.pr_number);
  const linkedIssue =
    item.issue && item.project
      ? issueIdentifier(item.project.key, item.issue.number)
      : null;
  const forgeUrl = pr?.url ?? item.pr_url;

  // The weight of PR, at a glance: GitHub puts it next to the title, and it's
  // the first question we ask ourselves before opening the Files tab.
  const additions = files.reduce((n, f) => n + f.additions, 0);
  const deletions = files.reduce((n, f) => n + f.deletions, 0);

  // The list knows the author (column `author_login`); the forge confirms it.
  // She wins as soon as she responds — same arbitration as for the state.
  const author = pr?.user ?? item.author;

  /**
   * “X wants to merge 3 commits into main from routine/audit” — the line that
   * GitHub poses under the title, and the only one that says BOTH branches: so far
   * minddy didn't display them anywhere, even though that's what answers "it's leaving
   * where, where does it come from? » before merging.
   *
   * The commit count comes from the forge when it serves it (GitHub puts it in
   * the GET of a PR); otherwise — GitLab — from the commit list already loaded for
   * its tab, and only if it is ENTIRE: a truncated list would announce
   * a false figure, and it is better to keep silent about the sentence than to lie about its figure.
   *
   * The subject is the name of the agent on a Numo PR: the forge account there
   * is the GitHub App bot, which minddy never shows (identity rule).
   */
  const commitCount =
    pr?.commitCount ?? (commitsTruncated || commits.length === 0 ? null : commits.length);
  const mergeSummary: React.ReactNode =
    pr?.base && pr?.head && commitCount !== null && (item.runId || author)
      ? t.rich(item.pr_state === "merged" ? "mergedCommits" : "wantsToMerge", {
          login: item.runId ? t("numoAuthor") : parseForgeLogin(author?.login ?? "").name,
          count: commitCount,
          base: pr.base,
          head: pr.head,
          author: (chunks) => (
            <span className="inline-flex items-center gap-1.5 font-medium text-foreground">
              {chunks}
              {/* The forge account is a bot, and it's not Numo: the
                  pellet lands on the NAME, like everywhere else. */}
              {!item.runId && author && parseForgeLogin(author.login).isBot ? <BotBadge /> : null}
            </span>
          ),
          branch: (chunks) => (
            <span className="rounded bg-muted px-1 py-0.5 font-mono text-[11px] text-foreground">
              {chunks}
            </span>
          ),
        })
      : null;

  // GitHub body of the PR, without the auto suffix “🤖 Generated by agent numo…”
  // (redundant with the “Generated by Numo” badge).
  const prDescription = (pr?.body ?? "").replace(/\n*🤖[^\n]*$/u, "").trim();

  // The full thread: messages AND activity, in the order everything happened.
  const feed = buildFeed(comments, timeline, reviewComments, commits);
  // The tab counter counts what is READ — messages and reviews that
  // say something — not the lines of activity, which are context.
  const conversationCount = feed.filter((e) => e.kind !== "event").length;

  return (
    // The envelope tells the WHOLE panel — body, thread, activity, comments of
    // line, composers — which PR he is talking about: which proxy to go through to
    // display an image of the forge, and which routes to ask for accounts
    // mentionable and hosting an attachment (MIN-162).
    <PrEndpointProvider endpoint={prEndpoint(item.prId)}>
    <div className="flex h-full min-h-0 flex-col">
      {/* Header: back (mobile) · identifier · actions */}
      {/* Header WITHOUT border: it's the fade of the thread that says it continues
          above, and a separate bar would cut it off from what it covers (even
          party than the agent conversation). */}
      <AppContentHeader contentClassName="gap-2 px-4 md:px-6">
        <Button
          variant="ghost"
          size="icon-sm"
          aria-label={t("backToList")}
          className="md:hidden"
          onClick={onBack}
        >
          <ChevronLeft />
        </Button>
        {/* The project orb opens the header, like that of a conversation
            the agent: the column no longer says the project line by line (it is
            written once, on the header of his accordion), and the detail is
            the place where we want to know which repository we are talking about. */}
        {item.project ? (
          <ProjectOrb
            seed={projectOrbSeed(item.project)}
            iconUrl={item.project.icon_url}
            className="size-4 shrink-0"
          />
        ) : null}
        <span className="flex min-w-0 items-center gap-1 font-mono text-sm">
          {forgeUrl ? (
            <a
              href={forgeUrl}
              target="_blank"
              rel="noreferrer"
              className="shrink-0 text-foreground outline-none hover:underline"
            >
              {identifier}
            </a>
          ) : (
            <span className="shrink-0 text-foreground">{identifier}</span>
          )}
          {linkedIssue ? (
            // The link icon makes this a navigable association, not a dependency.
            <Tooltip>
              <TooltipTrigger asChild>
                <button
                  type="button"
                  onClick={() => {
                    if (item.issue && item.project) onOpenIssue(item.issue.id, item.project.id);
                  }}
                  className="flex min-w-0 items-center gap-1 text-muted-foreground outline-none hover:text-foreground hover:underline"
                >
                  <Link2
                    data-testid="pr-issue-link-icon"
                    className="size-3.5 shrink-0"
                    aria-hidden
                  />
                  <span className="truncate">{linkedIssue}</span>
                </button>
              </TooltipTrigger>
              <TooltipContent side="bottom">{t("linkedIssue")}</TooltipContent>
            </Tooltip>
          ) : item.project ? (
            // Unattached: this is a NORMAL STATE since MIN-143 (the link comes
            // of a `MIN-42` convention in the branch, title or a line
            // Fixed — not a guess). The fact remains that the convention fails, and
            // that nothing knew how to place the link afterwards: the selector
            // takes the exact place of the missing ticket (MIN-163).
            <PrLinkIssue
              prId={item.prId}
              prState={item.pr_state}
              projectId={item.project.id}
              projectKey={item.project.key}
              onLinked={() => {
                onRefetchList();
                void refetchPr();
              }}
            />
          ) : (
            // No project resolved for this repository: there is no scope of
            // tickets to offer. We tell the state rather than offering an empty menu.
            <span className="font-sans text-xs text-muted-foreground/70">
              {t("noLinkedIssue")}
            </span>
          )}
        </span>
        {/* As long as the PR is ALIVE, its status is read on the left, against
            the identifier: the right belongs to the actions, which are what we
            look for. Completed (merged, closed), it's the opposite — the state BECOMES
            the news, and it will take the place of the actions, at the end of the
            line (see the right cluster below). */}
        {!isTerminal ? <PrStateBadge state={badgeState} icon /> : null}
        {isWorking ? (
          <span className="inline-flex items-center gap-1.5 text-xs text-muted-foreground">
            <Spinner />
            {t("numoWorking")}
          </span>
        ) : null}

        {isTerminal ? (
          // End of line of a completed PR: the only gesture left to it — reopen,
          // without confirmation, it does not destroy anything and the button next to it closes it
          // — then its STATE, last. The badge closes the line in both cases,
          // merged (nothing before it) as closed (the button before it): it is
          // always in the same place that we read what became of her.
          <div className="ml-auto flex items-center gap-1.5">
            {canReopen ? (
              <Button
                variant="outline"
                size="sm"
                onClick={() => void act("reopen")}
                disabled={!!acting}
              >
                {acting === "reopen" ? <Spinner /> : <RotateCcw />}
                {t("reopen")}
              </Button>
            ) : null}
            <PrStateBadge state={badgeState} icon />
          </div>
        ) : (
          // Under `lg`, secondary actions move into the overflow menu. The
          // remaining actions stay on the shared 60 px header line; if a long
          // translation still exceeds the pane, the header remains horizontally
          // reachable instead of growing vertically.
          <div className="ml-auto flex shrink-0 items-center justify-end gap-1.5">
            {/* ── Wide screen: each gesture has its name ─────────────────── */}
            <div className="hidden items-center gap-1.5 2xl:flex">
              {/* Request changes can launch Numo work and does not require a
                  connected forge identity, so it remains directly available. */}
              <Button variant="outline" size="sm" onClick={() => openReview("request_changes")}>
                <NumoIcon animated={false} />
                {t("reviewRequestChanges")}
              </Button>

              {/* Approve and comment require a forge identity. Numo review does
                  not, so it becomes a direct button when it is the only action. */}
              {canComment ? (
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="outline" size="sm">
                      {aiReviewActive ? <Spinner /> : null}
                      {t("review")}
                      <ChevronDown className="size-3.5" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem onSelect={() => openReview("approve")}>
                      <Check />
                      {t("reviewApprove")}
                    </DropdownMenuItem>
                    <DropdownMenuItem onSelect={() => openReview("comment")}>
                      <MessageSquare />
                      {t("reviewComment")}
                    </DropdownMenuItem>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem
                      // Keep the entry visible while its label explains why it is disabled.
                      disabled={
                        aiReviewActive || reviewUpToDate || !reviewExecutionConfigured
                      }
                      onSelect={openAiReviewDialog}
                    >
                      <NumoIcon animated={false} />
                      {aiReviewLabel}
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              ) : (
                <Button
                  variant="outline"
                  size="sm"
                  disabled={
                    aiReviewActive || reviewUpToDate || !reviewExecutionConfigured
                  }
                  onClick={openAiReviewDialog}
                >
                  {aiReviewActive ? <Spinner /> : <NumoIcon animated={false} />}
                  {/* Use the same status-aware label as the menu entry. */}
                  {aiReviewLabel}
                </Button>
              )}

              {canWrite ? (
                <Button
                  variant="destructive"
                  size="sm"
                  onClick={() => setConfirmAction({ kind: "close" })}
                  disabled={!!acting || isWorking}
                >
                  {acting === "close" ? <Spinner /> : <X />}
                  {t("closePullRequest")}
                </Button>
              ) : null}
            </div>

            {/* On narrow screens, actions stay available in one unlabeled menu.
                Numo work comes first, human review verdicts form the second
                section, and the destructive close action stays isolated last. */}
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  data-testid="pr-more-actions"
                  variant="outline"
                  size="icon-sm"
                  className={isDraft || !canWrite ? "2xl:hidden" : undefined}
                  aria-label={t("moreActions")}
                >
                  {aiReviewActive ? <Spinner /> : <MoreHorizontal />}
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem
                  data-testid="pr-action-numo-request"
                  className="2xl:hidden"
                  onSelect={() => openReview("request_changes")}
                >
                  <NumoIcon animated={false} />
                  {t("reviewRequestChanges")}
                </DropdownMenuItem>
                <DropdownMenuItem
                  data-testid="pr-action-numo-review"
                  className="2xl:hidden"
                  disabled={
                    aiReviewActive || reviewUpToDate || !reviewExecutionConfigured
                  }
                  onSelect={openAiReviewDialog}
                >
                  <NumoIcon animated={false} />
                  {aiReviewLabel}
                </DropdownMenuItem>
                {canComment ? (
                  <>
                    <DropdownMenuSeparator className="2xl:hidden" />
                    <DropdownMenuItem
                      data-testid="pr-action-approve"
                      className="2xl:hidden"
                      onSelect={() => openReview("approve")}
                    >
                      <Check />
                      {t("reviewApprove")}
                    </DropdownMenuItem>
                    <DropdownMenuItem
                      data-testid="pr-action-comment"
                      className="2xl:hidden"
                      onSelect={() => openReview("comment")}
                    >
                      <MessageSquare />
                      {t("reviewComment")}
                    </DropdownMenuItem>
                  </>
                ) : null}
                {canWrite ? (
                  <>
                    <DropdownMenuSeparator className="2xl:hidden" />
                    {!isDraft ? (
                      <DropdownMenuItem
                        data-testid="pr-action-convert-to-draft"
                        disabled={!!acting || isWorking}
                        onSelect={() => void act("convert_to_draft")}
                      >
                        {acting === "convert_to_draft" ? <Spinner /> : <GitPullRequestDraft />}
                        {t("convertToDraft")}
                      </DropdownMenuItem>
                    ) : null}
                    <DropdownMenuItem
                      data-testid="pr-action-close"
                      className="2xl:hidden"
                      variant="destructive"
                      disabled={!!acting || isWorking}
                      onSelect={() => setConfirmAction({ kind: "close" })}
                    >
                      <X />
                      {t("closePullRequest")}
                    </DropdownMenuItem>
                  </>
                ) : null}
              </DropdownMenuContent>
            </DropdownMenu>

            {isDraft && canWrite ? (
              <Button
                data-testid="pr-ready-for-review"
                size="sm"
                variant="outline"
                disabled={!!acting || isWorking}
                onClick={() => void act("ready_for_review")}
              >
                {acting === "ready_for_review" ? <Spinner /> : <GitPullRequest />}
                {t("openPullRequest")}
              </Button>
            ) : readiness ? (
              <PrReadinessControl
                readiness={readiness}
                providerName={REPO_PROVIDERS[item.provider].displayName}
                fallbackUrl={(blocker) =>
                  pr?.url ? blockerFallbackUrl(item.provider, pr.url, blocker) : null
                }
                canAct={canActOnBlocker}
                acting={maintenanceAction}
                onAction={(blocker) => void handleReadinessAction(blocker)}
                canMerge={!!canWrite}
                merging={acting === "merge" || isWorking}
                onMerge={(method) => setConfirmAction({ kind: "merge", method })}
              />
            ) : (
              <PrReadinessBadge readiness={null} />
            )}
          </div>
        )}
      </AppContentHeader>

      {/* Fade OFF under Files tab (MIN-182). A faded mask
          everything it contains, including sticky elements: the header of
          diff file should otherwise stop 2rem lower to remain clear,
          and a header that floats 32 px from the edge is seen. The fade says “there is
          text above” — the sticky header says it better, and naming the
          file. Under the other two tabs it remains, there is nothing sticking
          to protect.

          `onScroll` continues to run: the measure costs nothing and the fade
          just returns, without missed transitions, as soon as you change tabs. */}
      <div
        ref={feedFade.ref}
        onScroll={feedFade.scrollProps.onScroll}
        style={tab === "files" ? undefined : feedFade.scrollProps.style}
        // The VERTICAL padding has gone down a notch, on the envelope (MIN-182).
        // Measured: `position: sticky` fits on the CONTENT of the container
        // scrolling, not on its edge — a `py-6` here stopped the header from
        // 24 px file too low, and `scroll-padding-top: 0` changes nothing.
        // When lowered, it scrolls with the content and the header sticks to the banner.
        className="min-h-0 flex-1 overflow-y-auto px-4 md:px-6"
      >
        <div className="mx-auto flex max-w-3xl flex-col gap-6 py-6">
          {/* PR title + meta. The TITLE of the pull request, not that of the
              ticket: since MIN-143 they no longer come in pairs, and a PR
              human may have none. (Numo names his
              “MIN-42: <titre du ticket>” — the display does not change for them.) */}
          <div className="flex flex-col gap-2">
            <div className="flex min-w-0 items-start gap-2">
              <h1 className="min-w-0 flex-1 font-display text-2xl leading-tight font-semibold break-words">
                {pr?.title ?? item.title ?? item.issue?.title ?? identifier}
              </h1>
              {canWrite ? (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      data-testid="pr-edit-title"
                      variant="ghost"
                      size="icon-sm"
                      className="shrink-0"
                      aria-label={t("editPrTitle")}
                      onClick={() => {
                        setTitleDraft(pr?.title ?? item.title ?? "");
                        setEditingTitle(true);
                      }}
                    >
                      <Pencil className="size-4" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent side="top">{t("editPrTitle")}</TooltipContent>
                </Tooltip>
              ) : pr?.url ? (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      data-testid="pr-edit-title"
                      variant="ghost"
                      size="icon-sm"
                      className="shrink-0"
                      asChild
                    >
                      <a href={pr.url} target="_blank" rel="noreferrer" aria-label={t("editPrTitle")}>
                        <ExternalLink className="size-4" />
                      </a>
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent side="top">{t("editPrTitle")}</TooltipContent>
                </Tooltip>
              ) : null}
            </div>
            <div className="flex flex-wrap items-center gap-x-3 gap-y-1.5 text-xs text-muted-foreground">
              {/* Badge “generated by Numo”: only if a run REALLY carries
                  this PR. The session is that of the linked ticket (/agents is indexed
                  by outcome, all successive runs live there) → the badge leads there.
                  On a human PR, it is the author who takes this place. */}
              {item.runId ? (
                item.issue ? (
                  <Link href={`/agents?issue=${item.issue.id}`}>
                    <Badge
                      variant="secondary"
                      icon={<NumoIcon animated={false} />}
                      className="h-6 transition-colors hover:bg-muted"
                    >
                      {t("generatedByNumo")}
                    </Badge>
                  </Link>
                ) : (
                  <Badge variant="secondary" icon={<NumoIcon animated={false} />} className="h-6">
                    {t("generatedByNumo")}
                  </Badge>
                )
              ) : author ? (
                <span className="inline-flex items-center gap-1.5">
                  <UserAvatar
                    url={author.avatar_url}
                    seed={author.login}
                    className="size-4"
                  />
                  {/* The merger phrase already NAMES the author (“X wants to merge
                      3 commits in main…”): repeat “Opened by
                      side would be duplicate. The fallback keeps the name alone, as long as
                      branches or commit count are missing — the phrase
                      then ends with the login in both languages, and the
                      bot pellet lands after it, not in the middle. */}
                  {mergeSummary ?? (
                    <>
                      {t("openedBy", { login: parseForgeLogin(author.login).name })}
                      {parseForgeLogin(author.login).isBot ? <BotBadge /> : null}
                    </>
                  )}
                </span>
              ) : null}
              {/* PR from Numo: the badge took the place of the author, the sentence
                  so poses next to it - it is she who carries the branches. */}
              {item.runId && mergeSummary ? <span>{mergeSummary}</span> : null}
              {item.project ? (
                <span className="inline-flex items-center gap-1.5">
                  <ProjectOrb
                    seed={projectOrbSeed(item.project)}
                    iconUrl={item.project.icon_url}
                    className="size-3.5"
                  />
                  {item.project.name}
                </span>
              ) : null}
              {/* The diff in one number, in the place occupied by “PR #30 ↗” —
                  the identifier is mounted in the header, where it is
                  clickable towards the forge. Mute until files have
                  answered: “+0 −0” would read as an empty PR. */}
              {files.length > 0 ? (
                <span className="inline-flex items-center gap-1.5 font-medium tabular-nums">
                  <span className="text-green-700 dark:text-green-500">
                    +{format.number(additions)}
                  </span>
                  <span className="text-red-700 dark:text-red-500">
                    −{format.number(deletions)}
                  </span>
                </span>
              ) : null}
            </div>
          </div>

          {/* The only place to say which Git account is in use (MIN-144).
              It stays silent when everything is configured correctly. */}
          {!loading ? <PrViewerCallout viewer={viewer} repoUrl={pr?.url} /> : null}

          <ChecksBanner
            checks={checks}
            error={checksError}
            provider={item.provider}
            loading={loading}
          />

          {/* GitHub style tabs: the thread on one side, the code on the other. */}
          <Tabs
            value={tab}
            onValueChange={(v) => setTab(v as "activity" | "commits" | "files")}
          >
            <TabsList variant="line" className={TAB_LIST_DENSE}>
              <TabsTrigger value="activity" className={cn(TAB_TRIGGER_DENSE, "gap-1.5")}>
                {t("tabActivity")}
                {conversationCount > 0 ? (
                  <span className="text-xs text-muted-foreground">{conversationCount}</span>
                ) : null}
              </TabsTrigger>
              {/* Commits BEFORE files, like on GitHub: we read what
                  dials the PR before entering the code it changes. */}
              <TabsTrigger value="commits" className={cn(TAB_TRIGGER_DENSE, "gap-1.5")}>
                {t("tabCommits")}
                {commits.length > 0 ? (
                  <span className="text-xs text-muted-foreground">{commits.length}</span>
                ) : null}
              </TabsTrigger>
              <TabsTrigger value="files" className={cn(TAB_TRIGGER_DENSE, "gap-1.5")}>
                {t("tabFiles")}
                {files.length > 0 ? (
                  <span className="text-xs text-muted-foreground">{files.length}</span>
                ) : null}
              </TabsTrigger>
            </TabsList>

            {/* Thread: PR description opens discussion, comments
                GitHub follow, compose closes. */}
            <TabsContent value="activity" className="mt-4 flex flex-col gap-3">
              {loading || commentsLoading ? (
                <Skeleton className="h-16 rounded-lg" />
              ) : !prDescription && feed.length === 0 && !reviewCard ? (
                <p className="text-sm text-muted-foreground">{t("noComments")}</p>
              ) : (
                // Same cards as the issue comments (CommentCard): border,
                // background card, avatar/author/time header then markdown body.
                // The lines of activity are inserted between them, without a map.
                <ul className="flex flex-col gap-3">
                  {prDescription ? (
                    <ThreadComment
                      // The body of the PR is not a commentary, but it
                      // reacts like one: the server translates this zero into the
                      // subject each forge expects.
                      commentId={PR_BODY_COMMENT_ID}
                      user={pr?.user ?? null}
                      createdAt={pr?.createdAt ?? null}
                      body={prDescription}
                      // Quote feeds the bottom composer: without a git account it
                      // there is none, and the gesture would lead nowhere.
                      onQuoteReply={
                        canComment
                          ? () => quoteReply(prDescription, pr?.user?.login)
                          : undefined
                      }
                      reactions={threadReactions}
                    />
                  ) : null}
                  {feed.map((entry) => {
                    if (entry.kind === "event") {
                      return <PrTimelineRow key={entry.key} event={entry.event} />;
                    }
                    if (entry.kind === "review") {
                      return (
                        <PrTimelineReview
                          key={entry.key}
                          event={entry.event}
                          comments={entry.comments}
                          endpoint={prEndpoint(item.prId)}
                          threadStates={reviewThreads}
                          canComment={!!canComment}
                          canResolve={!!canWrite}
                          onChanged={refreshReviewState}
                        />
                      );
                    }
                    const c = entry.comment;
                    return (
                      <ThreadComment
                        key={entry.key}
                        commentId={c.id}
                        user={c.user}
                        createdAt={c.created_at}
                        body={c.body}
                        onQuoteReply={
                          canComment
                            ? () => quoteReply(c.body ?? "", c.user?.login)
                            : undefined
                        }
                        quotingNumo={isNumoComment(c.user?.login)}
                        reactions={threadReactions}
                      />
                    );
                  })}
                  {/* The proofreading session, where its verdict falls —
                      and clickable: this is how we will see what the agent has
                      read, and answered. */}
                  {reviewCard ? <PrReviewCard run={reviewCard} /> : null}
                </ul>
              )}

              {canComment ? (
                <div data-testid="pr-comment-composer-region" className="pt-1">
                  <PrCommentComposer
                    endpoint={prEndpoint(item.prId)}
                    value={commentBody}
                    onChange={setCommentBody}
                    onSubmit={() => void submitComment()}
                    posting={posting}
                    placeholder={t("commentPlaceholder")}
                    submitLabel={t("postComment")}
                    focusSignal={quoteFocus}
                  />
                </div>
              ) : null}

            </TabsContent>

            <TabsContent value="commits" className="mt-4">
              <PrCommits
                prId={item.prId}
                commits={commits}
                truncated={commitsTruncated}
                loading={commitsLoading}
                provider={item.provider}
              />
            </TabsContent>

            <TabsContent value="files" className="mt-4">
              {loading ? (
                <div className="flex flex-col gap-2">
                  <Skeleton className="h-6 w-40" />
                  <Skeleton className="h-40 rounded-md" />
                </div>
              ) : pr ? (
                <PrDiff
                  files={files}
                  endpoint={prEndpoint(item.prId)}
                  prUrl={pr.url}
                  provider={item.provider}
                  // Two distinct rights (MIN-144): comment on a line
                  // request `read`, resolve a thread is a write to the
                  // deposit. Confusing them would offer “Solve” for a 403.
                  readOnly={!canComment}
                  canResolve={canWrite}
                  reviewComments={reviewComments}
                  reviewThreads={reviewThreads}
                  reviewReactions={reviewReactions}
                  onCommentPosted={refreshReviewState}
                />
              ) : (
                <p className="text-sm text-muted-foreground">{t("prUnavailable")}</p>
              )}
            </TabsContent>
          </Tabs>
        </div>
      </div>

      <Dialog open={editingTitle} onOpenChange={(open) => !maintenanceAction && setEditingTitle(open)}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>{t("editPrTitle")}</DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground">
            {t("editPrTitleHint", { provider: REPO_PROVIDERS[item.provider].displayName })}
          </p>
          <input
            value={titleDraft}
            onChange={(event) => setTitleDraft(event.target.value)}
            maxLength={256}
            autoFocus
            className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"
            onKeyDown={(event) => {
              if (event.key === "Enter" && titleDraft.trim()) void saveTitle();
            }}
          />
          <DialogFooter>
            <Button variant="outline" disabled={!!maintenanceAction} onClick={() => setEditingTitle(false)}>
              {t("cancel")}
            </Button>
            <Button disabled={!!maintenanceAction || !titleDraft.trim()} onClick={() => void saveTitle()}>
              {maintenanceAction ? <Spinner /> : <Pencil />}
              {t("savePrTitle")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Confirmation fusionner / refuser */}
      <Dialog
        open={!!confirmAction}
        onOpenChange={(next) => {
          if (!next && !acting) setConfirmAction(null);
        }}
      >
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>
              {confirmAction?.kind === "merge" ? t("confirmMergeTitle") : t("confirmCloseTitle")}
            </DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground">
            {confirmAction?.kind === "merge"
              ? t("confirmMergeDescription")
              : t("confirmCloseDescription")}
          </p>
          <DialogFooter>
            <Button variant="outline" disabled={!!acting} onClick={() => setConfirmAction(null)}>
              {t("cancel")}
            </Button>
            <Button
              variant={confirmAction?.kind === "close" ? "destructive" : "default"}
              disabled={!!acting}
              onClick={() => {
                if (!confirmAction) return;
                if (confirmAction.kind === "merge") void act("merge", confirmAction.method);
                else void act("close");
              }}
            >
              {acting ? <Spinner /> : null}
              {confirmAction?.kind === "merge" ? t("merge") : t("close")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* “Have it checked by Numo” — the only choice to make is the model, and
          it is done HERE, with the click: the default of the instance suits most
          time, a big PR sometimes deserves better. The choice is made for
          next time; “mindy default” clears it. */}
      <FormDialog
        open={aiReviewDialog}
        onOpenChange={(next) => {
          if (!next && !startingAiReview) setAiReviewDialog(false);
        }}
        title={t("aiReview")}
        description={t("numoReviewDialogDescription")}
        className="sm:max-w-md"
        submitLabel={t("numoReviewStart")}
        submitIcon={startingAiReview ? <Spinner /> : <NumoIcon animated={false} />}
        submitting={startingAiReview}
        cancelLabel={t("cancel")}
        onCancel={() => setAiReviewDialog(false)}
        onSubmit={() => void startAiReview()}
      >
          <div className="flex flex-col gap-1.5">
            <span className="text-xs text-muted-foreground">{t("numoReviewModelLabel")}</span>
            <ModelCombobox
              // Catalog of the platform key, filtered tool-calling: the review
              // runs on it regardless of the BYOK of the account (`review`).
              scope="review"
              value={aiReviewModel}
              onChange={setAiReviewModel}
              defaultLabel={t("numoReviewModelInstance")}
              defaultModelId={reviewSession.model?.instance ?? null}
              placeholder={tAgent("modelSearchPlaceholder")}
              emptyLabel={tAgent("modelSearchEmpty")}
              loadingLabel={tAgent("modelSearchLoading")}
              freeTextLabel={(q) => tAgent("modelUseCustom", { model: q })}
              disabled={startingAiReview}
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <span className="text-xs text-muted-foreground">{tAgent("reasoning")}</span>
            <ReasoningCombobox
              value={aiReviewReasoningLevel}
              onChange={setAiReviewReasoningOverride}
              disabled={startingAiReview}
              levels={aiReviewReasoningLevels}
              variant="field"
            />
          </div>
      </FormDialog>

      {/* Review dialogue — all three verdicts share the same form;
          only the box “and restart Numo” distinguishes the request for changes. */}
      <FormDialog
        open={!!reviewVerdict}
        onOpenChange={(next) => {
          if (!next && !submitting) setReviewVerdict(null);
        }}
        title={t(
          reviewVerdict === "approve"
            ? "reviewApproveTitle"
            : reviewVerdict === "comment"
              ? "reviewCommentTitle"
              : "reviewRequestChangesTitle",
        )}
        className="sm:max-w-md"
        submitLabel={reviewSubmitLabel}
        submitDisabled={reviewSubmitDisabled}
        submitting={submitting}
        submitIcon={submitting ? <Spinner /> : null}
        cancelLabel={t("cancel")}
        onCancel={() => setReviewVerdict(null)}
        onSubmit={() => void submitReview()}
        dictation={{
          onTranscription: (text) =>
            setReviewMessage((value) => `${value}${value ? " " : ""}${text}`),
          disabled: submitting,
        }}
      >
          {/* The two modes of requesting changes. The second exists
              because the instructions are almost always the SAME — “take this
              that we wrote to you and correct it” — and that we retyped it by hand
              while the remarks are already on the PR, readable by the agent.
              Absent from the other two verdicts: approve and comment do not
              que parler, ils n'ont qu'un mode. */}
          {reviewVerdict === "request_changes" ? (
            <Tabs
              value={reviewMode}
              onValueChange={(v) => switchReviewMode(v as "write" | "findings")}
            >
              <TabsList className="w-full">
                <TabsTrigger value="write" className="flex-1">
                  {t("reviewModeWrite")}
                </TabsTrigger>
                {canRelaunch ? (
                  <TabsTrigger value="findings" className="flex-1">
                    {t("reviewModeFindings")}
                  </TabsTrigger>
                ) : (
                  // Numo has never pushed this PR: it has no branch to
                  // restart, so nothing to correct. Disabled WITH his reason —
                  // a silent tab would leave users searching.
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <span tabIndex={0} className="flex-1">
                        <TabsTrigger value="findings" disabled className="w-full">
                          {t("reviewModeFindings")}
                        </TabsTrigger>
                      </span>
                    </TooltipTrigger>
                    <TooltipContent side="bottom">
                      {t("reviewFindingsUnavailable")}
                    </TooltipContent>
                  </Tooltip>
                )}
              </TabsList>
            </Tabs>
          ) : null}

          <Textarea
            value={reviewMessage}
            onChange={(e) => setReviewMessage(e.target.value)}
            // Same shortcut as the other composers of the app, adjustment of
            // account included: ⌘/Ctrl+Enter send (or Enter only), Shift+Enter
            // goes to the line. The button is only accessible if the review has
            // what to leave — the guard is his, read again here.
            onKeyDown={(e) => {
              if (!isSend(e)) return;
              e.preventDefault();
              if (!reviewSubmitDisabled) void submitReview();
            }}
            placeholder={t(
              reviewVerdict === "approve" ? "reviewApprovePlaceholder" : "reviewPlaceholder",
            )}
            rows={reviewMode === "findings" ? 5 : 4}
            autoFocus
            className="resize-none bg-card"
          />

          {/* What this mode REALLY does, once said: text is a
              deposit for Numo, not a review — nothing leaves under your name. */}
          {reviewVerdict === "request_changes" && reviewMode === "findings" ? (
            <p className="text-xs text-muted-foreground">{t("reviewFindingsHint")}</p>
          ) : null}

          {/* Without a git account, the verdict has no one to sign it (MIN-144):
              only the raise leaves. Say it here rather than letting people believe
              a published review. */}
          {reviewVerdict === "request_changes" && reviewMode === "write" && !canComment ? (
            <p className="text-xs text-muted-foreground">{t("reviewNoVerdictHint")}</p>
          ) : null}

          {/* The gesture that minddy has and that GitHub does not: the request for
              changes can restart Numo on this same PR (MIN-68).
              ABSENT on a PR without a run (MIN-143): Numo inherits the job by
              PREVIOUS runs of this lineage — his ticket, or the PR
              itself when it does not have one (MIN-292) —, and a human PR does not
              has none: he would start from a new branch instead of starting again
              this one. The gesture is hidden rather than broken. */}
          {reviewVerdict === "request_changes" && reviewMode === "write" && canRelaunch ? (
            item.busyRunId ? (
              <Tooltip>
                <TooltipTrigger asChild>
                  <span tabIndex={0} className="flex items-center gap-2">
                    <Checkbox checked={false} disabled />
                    <span className="text-sm text-muted-foreground">
                      {t("reviewRelaunchNumo")}
                    </span>
                  </span>
                </TooltipTrigger>
                <TooltipContent side="bottom">{tAgent("errorAlreadyRunning")}</TooltipContent>
              </Tooltip>
            ) : (
              <label className="flex items-center gap-2">
                <Checkbox
                  checked={relaunch}
                  onCheckedChange={(v) => setRelaunch(v === true)}
                  disabled={submitting}
                />
                <span className="text-sm">{t("reviewRelaunchNumo")}</span>
              </label>
            )
          ) : null}

          {/* Settings are only visible for the path that actually launches
              a run now. Sending a review alone only writes about the
              forge: offer it an environment, a model or reasoning
              would be a false promise. */}
          {reviewVerdict === "request_changes" && relaunching ? (
            <div className="flex flex-wrap items-center gap-1.5">
              {localRepo.linked ? (
                <EnvironmentCombobox
                  value={environment}
                  onChange={setEnvironment}
                  localAvailable={localRepo.available}
                  cloudAvailable={cloudExecutionConfigured}
                  executionBackend={executionBackend}
                  folder={localRepo.state?.status === "ready" ? localRepo.state.folder : null}
                  needsAttach={localRepo.state?.status !== "ready"}
                  onAttach={() => {
                    void localRepo.attach().then((next) => {
                      if (next?.status === "ready") setEnvironment("local");
                      else if (next && next.status === "invalid") {
                        toast.error(tAgent(LOCAL_REPO_ERROR_KEYS[next.reason]));
                      }
                    });
                  }}
                  disabled={submitting || localRepo.busy}
                />
              ) : null}
              <ModelCombobox
                variant="compact"
                value={model}
                onChange={setModel}
                defaultLabel={tAgent("modelDefault")}
                defaultModelId={defaultModel ?? providerDefaultModel}
                placeholder={tAgent("modelSearchPlaceholder")}
                emptyLabel={tAgent("modelSearchEmpty")}
                loadingLabel={tAgent("modelSearchLoading")}
                freeTextLabel={(q) => tAgent("modelUseCustom", { model: q })}
                disabled={submitting}
              />
              <ReasoningCombobox
                value={reasoningLevel}
                onChange={setReasoningOverride}
                disabled={submitting}
                levels={reasoningLevels}
              />
              {relaunchBackendUnavailable ? (
                <p className="w-full text-xs text-amber-600 dark:text-amber-400">
                  {tAgent("errorExecutionBackendUnavailable")}
                </p>
              ) : null}
            </div>
          ) : null}

      </FormDialog>
      <LocalIssueRunConfirmation
        open={confirmLocalRelaunch}
        folder={localRepo.state?.status === "ready" ? localRepo.state.folder : ""}
        onOpenChange={setConfirmLocalRelaunch}
        onConfirm={() => {
          setConfirmLocalRelaunch(false);
          void submitReview(true);
        }}
      />
    </div>
    </PrEndpointProvider>
  );
}
