"use client";

import { useState, type FormEvent } from "react";
import { Loader2, SendHorizonal, Sparkles } from "lucide-react";
import { cn } from "mangue-ui/lib/utils";
import { Button } from "mangue-ui/components/ui/button";
import { Input } from "mangue-ui/components/ui/input";

/** The pages that carry a FAQ section, mirroring `FAQ_SECTIONS` on the server. */
export type FaqAskSection = "landing" | "pricing" | "mcp";

export interface FaqAskStrings {
  title: string;
  placeholder: string;
  submit: string;
  submitAria: string;
  loading: string;
  disclaimer: string;
  error: string;
}

type Status =
  | { kind: "idle" }
  | { kind: "loading" }
  | { kind: "answered"; answer: string }
  | { kind: "failed" };

/**
 * The question box of a FAQ section (MIN-590): the visitor types their own
 * question, presses Enter, and the answer is generated by an AI grounded in
 * the product knowledge (`app/api/faq/answer/route.ts`).
 *
 * The strings cross as props, not through `useTranslations`: this is a
 * marketing page, and the public browser feed carries only the whitelisted
 * namespaces (`lib/public-client-messages.ts`) — same envelope as the
 * dictation demo.
 */
export function FaqAsk({
  section,
  locale,
  strings,
}: {
  section: FaqAskSection;
  locale: string;
  strings: FaqAskStrings;
}) {
  const [question, setQuestion] = useState("");
  const [status, setStatus] = useState<Status>({ kind: "idle" });

  const ask = async (event: FormEvent) => {
    event.preventDefault();
    const asked = question.trim();
    if (!asked || status.kind === "loading") return;
    setStatus({ kind: "loading" });
    try {
      const res = await fetch("/api/faq/answer", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question: asked, section, locale }),
      });
      const data = (await res.json().catch(() => null)) as
        | { answer?: string }
        | null;
      if (res.ok && typeof data?.answer === "string" && data.answer) {
        setStatus({ kind: "answered", answer: data.answer });
        setQuestion("");
      } else {
        setStatus({ kind: "failed" });
      }
    } catch {
      setStatus({ kind: "failed" });
    }
  };

  return (
    <div className="mt-6 rounded-xl border border-border/60 bg-muted/20 p-5">
      <p className="flex items-center gap-2 text-sm font-medium">
        <Sparkles className="size-4 shrink-0 text-muted-foreground" aria-hidden />
        {strings.title}
      </p>
      <form
        className="mt-3 flex flex-col gap-2 sm:flex-row"
        onSubmit={(event) => void ask(event)}
      >
        <Input
          value={question}
          placeholder={strings.placeholder}
          maxLength={500}
          className="flex-1"
          aria-label={strings.placeholder}
          disabled={status.kind === "loading"}
          onChange={(event) => setQuestion(event.target.value)}
        />
        <Button type="submit" variant="outline" disabled={status.kind === "loading" || !question.trim()}>
          {status.kind === "loading" ? (
            <Loader2 className="size-4 animate-spin" aria-hidden />
          ) : (
            <SendHorizonal className="size-4" aria-hidden />
          )}
          <span aria-hidden={status.kind === "loading"}>
            {status.kind === "loading" ? strings.loading : strings.submit}
          </span>
          <span className="sr-only">{strings.submitAria}</span>
        </Button>
      </form>

      <div aria-live="polite">
        {status.kind === "answered" ? (
          <p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-foreground">
            {status.answer}
          </p>
        ) : null}
        {status.kind === "failed" ? (
          <p className={cn("mt-3 text-sm text-destructive")}>{strings.error}</p>
        ) : null}
      </div>

      <p className="mt-3 text-xs text-muted-foreground">{strings.disclaimer}</p>
    </div>
  );
}
