// GENERATED — do not edit by hand.
//
// Produced by `node captures/lib/publish.mjs` from actual content of
// `public/captures/`. Each entry is named `<slot>-<locale>-<theme>`
// and guarantees that the file exists: the landing therefore never points to a
// image missing, it returns its reservation frame instead.

export const PUBLISHED_SCREENSHOTS: ReadonlySet<string> = new Set([
  "featureCycle-en-dark",
  "featureCycle-en-light",
  "featureCycle-fr-dark",
  "featureCycle-fr-light",
  "featurePalette-en-dark",
  "featurePalette-en-light",
  "featurePalette-fr-dark",
  "featurePalette-fr-light",
  "feedbackBoard-en-dark",
  "feedbackBoard-en-light",
  "feedbackBoard-fr-dark",
  "feedbackBoard-fr-light",
  "feedbackInbox-en-dark",
  "feedbackInbox-en-light",
  "feedbackInbox-fr-dark",
  "feedbackInbox-fr-light",
  "heroBoard-en-dark",
  "heroBoard-en-light",
  "heroBoard-fr-dark",
  "heroBoard-fr-light",
  "numoPanel-en-dark",
  "numoPanel-en-light",
  "numoPanel-fr-dark",
  "numoPanel-fr-light",
  "pagesEditor-en-dark",
  "pagesEditor-en-light",
  "pagesEditor-fr-dark",
  "pagesEditor-fr-light",
  "scratchpad-en-dark",
  "scratchpad-en-light",
  "scratchpad-fr-dark",
  "scratchpad-fr-light",
  "workflowAgent-en-dark",
  "workflowAgent-en-light",
  "workflowAgent-fr-dark",
  "workflowAgent-fr-light",
  "workflowIssue-en-dark",
  "workflowIssue-en-light",
  "workflowIssue-fr-dark",
  "workflowIssue-fr-light",
  "workflowPr-en-dark",
  "workflowPr-en-light",
  "workflowPr-fr-dark",
  "workflowPr-fr-light",
]);
