import { MCP_CLIENT_TOOL_NAMES } from "@/lib/mcp-client-tools";
import {
  ISSUE_TOOL_NAMES,
  PR_TOOL_NAMES,
  PROJECT_PR_TOOL_NAMES,
  SCRATCHPAD_TOOL_NAMES,
} from "../platform-tool-names";
import { agentToolsFor, type AgentToolDef } from "../tools";
import { opencodeToolDir } from "./opencode-config";
import { isLocalJob, type VmJob } from "./protocol";

/**
 * DOMAIN TOOLS, WRITTEN FOR OPENCODE (MIN-286, lot 1) — the ~35 tools
 * which does NOT stop being our code, rendered in the form that opencode loads.
 *
 * THE FILE RULE, and it is she who decides everything else: **there is no
 * second table**. Schemas, descriptions, anchor targeting
 * (`TARGET_SUFFIX`), structural withdrawals (`web_search` outside OpenRouter,
 * `report_verdict` outside chain, `create_routine` outside interactive session)
 * come from `agentToolsFor` ([tools.ts](../tools.ts)) — the SAME definitions
 * than today, rendered differently. Copying these diagrams here would have created two
 * truths which diverge at the first ticket, and the divergence would only be seen
 * in the behavior of a model.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT WAS MEASURED ON `opencode-ai@1.18.16`, and which is not written anywhere
 *
 * 1. **A tool is declared in TypeScript, and two forms are accepted — one
 * only one is usable.** The bare object (`export default { description, args,
 * execute }`) traite `args` as a map *name → schema*, and **renders EVERYTHING
 * obligatory**: passing a complete JSON Schema produces an absurd schema
 * (`required: ["properties", "additionalProperties"]`, measured) than the model
 * receive as is. The form `tool({...})` of `@opencode-ai/plugin`, for its part,
 * accepts `tool.schema` (zod) with `.optional()` and `.enum()`, and returns the
 * exact diagram. **Our tools have optional parameters everywhere**: this is
 * therefore `tool()`, and that is why this module EMITS zod CODE rather than
 *    de recopier un JSON Schema.
 * 2. **`@opencode-ai/plugin` does not have to be installed**: the TypeScript runtime of
 * binary solves it alone. No `node_modules` to place in the microVM.
 * 3. **Tools can live OUTSIDE THE DEPOSIT** — `$XDG_CONFIG_HOME/opencode/tool/`
 * is loaded as `.opencode/tool/` of the project (measured: served AND called).
 * It is essential, not a preference: in the deposit, they would enter
 * in the `git add -A` at the end of the turn and would find themselves committed to
 * the user. Hence `opencodeToolDir`, under the run harness.
 * 4. **`process.env` is readable from a tool** (measured) — this is how
 * the supervisor address goes down, without any value being written in
 * hard in the generated code.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY THE TOOL GOES THROUGH THE SUPERVISOR, AND NOT DIRECTLY THROUGH THE MANAGEMENT PLAN
 * CONTROL
 *
 * The framing said “each one a `fetch` to the control plane”. A local hop
 * moreover holds the same guarantee — it is the supervisor who makes the outgoing call,
 * therefore the identity remains proven by the OIDC of the firewall, and no secret enters
 * in the VM — and it does three things that a direct call would make impossible:
 *
 * - **TOUR counters**: the web search limit
 * (`webSearchMax`), image cap (`MAX_IMAGES_PER_TURN`) and anchors
 * reviews already asked are states of the tour. A tool without memory
 * would lose, and the control plan counts for nothing — it charges what it is charged
 *   demande ;
 * - **`create_pr`**, which is cut in two by construction: the VM PUSHES, the
 * OPEN function. Only the supervisor has the deposit;
 * - **`validate_changes`**, which runs repository checks where the supervisor
 * can see the repository and returns their report to the model;
 * - **delivery rules** (gate, self-review, plan closure), which must
 * see making calls.
 *
 * The generated code does not know any of this: it posts a JSON and returns this
 * that we answer him. That's the point — a generated tool that contains logic
 * is a tool that is maintained in two copies.
 */

/** The header placed on each generated file: no one edits it by hand. */
const HEADER = `// Generated by lib/server/agent/vm/opencode-tools.ts — DO NOT EDIT.\n// MIN-286: this file is rewritten each turn from the definitions in tools.ts.\n`;

/**
 * The variable which carries the address of the supervisor. Read by the generated code, placed
 * by the supervisor at startup: the port is chosen at runtime, it cannot
 * therefore not be written to the file.
 */
export const SUPERVISOR_URL_ENV = "MDY_SUPERVISOR_URL";

/** Per-turn bearer credential for the local tool bridge. */
export const SUPERVISOR_TOKEN_ENV = "MDY_SUPERVISOR_TOKEN";

/**
 * THE HEADER WHICH SAYS “THIS ANSWER HAS AN IMAGE” (MIN-286, lot 3).
 *
 * The bridge responds to TEXT in the overwhelming majority of cases, and the tool generated
 * makes it as is. Only one answer does not fit in there: `read_resource` on
 * a model, which must become a **message attachment** so that the
 * model the PATH instead of reading the data sheet (measured, file §2.22).
 *
 * It is announced by a header rather than by the shape of the body: it is the only
 * way to distinguish the two without a domain tool which would render
 * legitimately a `{output, attachments}` object is not taken for an envelope.
 * The two existing paths therefore do not move one byte.
 */
export const TOOL_ATTACHMENTS_HEADER = "x-minddy-attachments";

/**
 * The tools which become DOMAIN tools, that is to say those whose
 * execution lives on the server side. Derivative of routing `Set`
 * ([platform-tool-names.ts](../platform-tool-names.ts)) rather than rewritten:
 * these are the same names as `exec-tool.ts` route today.
 *
 * The three additions, and why each is not in these `Set`:
 * - `create_pr` — cut in two (the VM pushes, the function opens);
 * - `web_search` — billed and capped by us, and not served anyway
 * by opencode on OpenRouter;
 * - `ask_user` is NOT there: it has a native counterpart (`question`), which the
 * supervisor plugs into our question queue.
 *
 * `update_plan` is NO LONGER there: it never had a server-side handler (this is
 * a CONTROL tool, which the home loop executed itself without exiting),
 * so each call went back to `404: unknown platform tool: update_plan` — the
 * thread checklist remained empty on all opencode runs. He passed to
 * tools LOCAL, where it should have been from the start.
 */
export const DOMAIN_TOOL_NAMES: ReadonlySet<string> = new Set([
  ...MCP_CLIENT_TOOL_NAMES,
  ...ISSUE_TOOL_NAMES,
  ...SCRATCHPAD_TOOL_NAMES,
  ...PR_TOOL_NAMES,
  ...PROJECT_PR_TOOL_NAMES,
  "create_pr",
  "web_search",
]);

/**
 * LOCAL TOOLS — those that the SUPERVISOR runs in the microVM, without ever
 * sortir d'elle (MIN-286, lot 3 ; dossier §3.2).
 *
 * `update_plan` is, and that's what was missing: it's a CONTROL tool,
 * no domain. It doesn't execute anything — it emits the `plan_update` event that the thread
 * renders it as a checklist, and mirrors the states to the ticket plan. The loop
 * house treated it like this ([agent-loop.ts](../agent-loop.ts)); stored aside
 * domain, he went to the control plane, which never had a handler of his own
 * oppose — 404 on each call, dead checklist.
 *
 * `run_background` was the only one until then: `bash` does not have a background mode, and the register
 * opencode jobs serves `task`, not the shell. The withdrawal that held until now — say
 * to the model to launch its server in `&` in the persistent shell — carried the
 * doctrine (“run the code for real”) without lifecycle management: nothing
 * killed the server before delivery and its output was not bounded. The tool is
 * therefore backed by [background.ts](../background.ts).
 *
 * It crosses the same bridge as domain tools: the generated file is
 * identical, it is the bridge which executes it instead of forwarding it.
 */
export const LOCAL_TOOL_NAMES: ReadonlySet<string> = new Set([
  "run_background",
  "update_plan",
  "validate_changes",
  // The project catalog carries paths, so it can only be resolved
  // in the local harness where the desktop app built it.
  "list_projects",
]);

/**
 * The domain tools SERVED by this tour, with their descriptions already cut
 * to its anchorage. `agentToolsFor` does all the work — we only keep those whose
 * the execution is ours, the others being rendered by opencode.
 */
export function domainToolsFor(job: VmJob): AgentToolDef[] {
  return toolsFor(job).filter((t) => DOMAIN_TOOL_NAMES.has(t.function.name));
}

/**
 * LOCAL tools served by this tour. The supervisor uses it to not wire
 * `run_background` only where it is offered — a replay session does not launch
 * nothing in the background, and a tool routed without being served is a tool that is maintained for
 * personne.
 */
export function localToolsFor(job: VmJob): AgentToolDef[] {
  return toolsFor(job).filter((t) => LOCAL_TOOL_NAMES.has(t.function.name));
}

/**
 * Everything we WRITE in the tools folder: domain + local. A session of
 * The canonical manifest is rendered for every anchor without a second filter here.
 */
function bridgedToolsFor(job: VmJob): AgentToolDef[] {
  return toolsFor(job).filter(
    (t) =>
      DOMAIN_TOOL_NAMES.has(t.function.name) ||
      LOCAL_TOOL_NAMES.has(t.function.name),
  );
}

/** Exact per-run capability set enforced by both generation and dispatch. */
export function bridgedToolNamesFor(job: VmJob): ReadonlySet<string> {
  return new Set(bridgedToolsFor(job).map((tool) => tool.function.name));
}

function toolsFor(job: VmJob): AgentToolDef[] {
  return agentToolsFor({
    anchor: job.anchor,
    webSearch: job.webSearch,
    webSearchMax: job.webSearchMax,
    model: job.model,
    images: job.imageInput,
    subagentModels: job.subagents.models,
    chain: job.chain,
    interactive: job.interactive,
    // No push URL → no forge: `create_pr` and the project-PR inventory are
    // not served (local run on a project with no linked repository).
    repo: job.authUrl != null,
    // MIN-293: `run_background` is not served on a machine. The condition
    // is placed HERE, in the only harness tool factory, and not one
    // second time in `localToolsFor` — the bridge only writes what is served,
    // and the supervisor only wires what the bridge has written.
    local: isLocalJob(job),
  });
}

type JsonSchema = {
  additionalProperties?: boolean;
  type?: string;
  description?: string;
  enum?: unknown[];
  items?: JsonSchema;
  properties?: Record<string, unknown>;
  required?: string[];
};

/** `"a\nb"` → a safe TypeScript literal. `JSON.stringify` escapes everything. */
function literal(value: string): string {
  return JSON.stringify(value);
}

/**
 * THE TOOLS THAT OUR DESCRIPTIONS QUOTE, SAY WITH OPENCODE NAMES (MIN-286).
 *
 * `agentToolsFor` is the only source of the descriptions, and they talk about tools
 * VOISINS : « use run_command for those », « exactly like edit_file », « download
 * them with run_command”. These names are those of the house loop, and the
 * model that reads them under opencode calls a tool that does not exist — while
 * its prompt system cites the correct ones ([prompt.ts](../prompt.ts),
 * `OPENCODE_TOOL_NAMES`). Two truths in the same context, and a burnt round
 * to find out which one is correct.
 *
 * The table is that of the events translator ([opencode-events.ts](opencode-events.ts),
 * `TOOL_NAMES`) read backwards, plus `list_dir` — at opencode, it's `read` which
 * list. An unopposed name (`apply_edits`) is not there: rename it
 * would promise something else rather than nothing.
 */
const OPENCODE_NAME_FOR: Record<string, string> = {
  read_file: "read",
  list_dir: "read",
  write_file: "write",
  edit_file: "edit",
  run_command: "bash",
  ask_user: "question",
  spawn_agent: "task",
};

const OPENCODE_NAME_RE = new RegExp(
  `\\b(${Object.keys(OPENCODE_NAME_FOR).join("|")})\\b`,
  "g",
);

/** A description of `tools.ts`, resized to the names that opencode actually uses. */
export function retargetToolNames(text: string): string {
  return text.replace(
    OPENCODE_NAME_RE,
    (name) => OPENCODE_NAME_FOR[name] ?? name,
  );
}

/**
 * A JSON schema, rendered as an expression `tool.schema.…`.
 *
 * What this translator covers is exactly what `tools.ts` uses —
 * `string`, `number`, `boolean`, `array` (with `items`), `object` (nested),
 * `enum`, `description`. The rest **rises**, and this is deliberate: a pattern that we
 * ne sait pas traduire deviendrait sinon un `any` silencieux, donc un tool dont
 * the model no longer knows the form. An error when starting the tour is seen;
 * a parameter disappeared, no.
 */
export function schemaExpression(schema: JsonSchema, path = "args"): string {
  const describe = (expr: string) =>
    schema.description
      ? `${expr}.describe(${literal(retargetToolNames(schema.description))})`
      : expr;

  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    // The enums of `tools.ts` are all strings; an enum of something else
    // would not have an obvious translation, and it is better to know it here.
    if (!schema.enum.every((v) => typeof v === "string")) {
      throw new Error(`${path}: enum non textuel, sans traduction`);
    }
    return describe(`tool.schema.enum(${JSON.stringify(schema.enum)})`);
  }

  switch (schema.type) {
    case "string":
      return describe("tool.schema.string()");
    case "number":
    case "integer":
      return describe("tool.schema.number()");
    case "boolean":
      return describe("tool.schema.boolean()");
    case "array": {
      if (!schema.items) throw new Error(`${path}: tableau sans \`items\``);
      return describe(
        `tool.schema.array(${schemaExpression(schema.items, `${path}[]`)})`,
      );
    }
    case "object": {
      const properties = schema.properties ?? {};
      const required = new Set(schema.required ?? []);
      const entries = Object.entries(properties).map(([name, raw]) => {
        const inner = schemaExpression(raw as JsonSchema, `${path}.${name}`);
        return `    ${JSON.stringify(name)}: ${inner}${required.has(name) ? "" : ".optional()"},`;
      });
      const passthrough = schema.additionalProperties === true ? ".passthrough()" : "";
      return describe(`tool.schema.object({\n${entries.join("\n")}\n  })${passthrough}`);
    }
    default:
      throw new Error(`${path}: type ${String(schema.type)} sans traduction`);
  }
}

/** The `args` card of a tool: one property per line, optional unless required. */
function argsBlock(def: AgentToolDef): string {
  const { properties, required } = def.function.parameters;
  const req = new Set(required ?? []);
  const entries = Object.entries(properties).map(([name, raw]) => {
    const expr = schemaExpression(
      raw as JsonSchema,
      `${def.function.name}.${name}`,
    );
    return `    ${JSON.stringify(name)}: ${expr}${req.has(name) ? "" : ".optional()"},`;
  });
  return entries.length ? `{\n${entries.join("\n")}\n  }` : "{}";
}

/**
 * THE FILE OF A TOOL. Always the same shape, description and diagram
 * close: he posts, he returns.
 *
 * `JSON.stringify` of the result, and not formatting: that's what the loop
 * already done today on the model side, and a second formatting here would be a
 * second thing to keep in phase with the other motor during the switch.
 *
 * A transport failure is NOT a rising exception: the model should read
 * error and be able to try again or do something else. A tool that lifts cuts the
 * round, which is the more expensive way of saying “try again”.
 *
 * THE ONLY BRANCH: the `TOOL_ATTACHMENTS_HEADER` header, which announces an image
 * (`read_resource` on a model). The body is then an **envelope**
 * `{output, attachments}` that the tool renders as is — it is the rich form of the
 * `ToolResult` of `@opencode-ai/plugin`, and opencode transforms it into a part
 * `image_url` of a message `user` posted after the round (measured, file §2.22).
 * An illegible envelope falls on the text: a lost model is better
 * qu'un round perdu.
 */
export function renderOpencodeTool(def: AgentToolDef): string {
  const name = def.function.name;
  return `${HEADER}import { tool } from "@opencode-ai/plugin";

export default tool({
  description: ${literal(retargetToolNames(def.function.description))},
  args: ${argsBlock(def)},
  async execute(args, ctx) {
    const base = process.env[${literal(SUPERVISOR_URL_ENV)}];
    const token = process.env[${literal(SUPERVISOR_TOKEN_ENV)}];
    if (!base || !token) return "minddy tool bridge is not configured for this turn.";
    try {
      const res = await fetch(base + "/tool/" + ${literal(name)}, {
        method: "POST",
        headers: { "content-type": "application/json", authorization: "Bearer " + token },
        body: JSON.stringify({ args, callID: ctx?.callID, sessionID: ctx?.sessionID }),
        signal: ctx?.abort,
      });
      const text = await res.text();
      if (!res.ok) return "minddy tool ${name} failed (HTTP " + res.status + "): " + text.slice(0, 500);
      if (res.headers.get(${literal(TOOL_ATTACHMENTS_HEADER)})) {
        try {
          const envelope = JSON.parse(text);
          if (envelope && typeof envelope.output === "string" && Array.isArray(envelope.attachments)) {
            return { output: envelope.output, attachments: envelope.attachments };
          }
        } catch {}
      }
      return text;
    } catch (err) {
      return "minddy tool ${name} could not reach the harness: " + (err instanceof Error ? err.message : String(err));
    }
  },
});
`;
}

/** A file to write in the microVM: absolute path and content. */
export interface OpencodeToolFile {
  path: string;
  content: string;
}

/**
 * ALL domain tools in one turn, ready to write. The supervisor asks this
 * table as is before starting the server.
 *
 * The file name IS the name of the tool: this is what opencode records, and the
 * to diverge would amount to serving `read_issue` under the name `read-issue.ts`.
 */
export function opencodeToolFiles(job: VmJob): OpencodeToolFile[] {
  return bridgedToolsFor(job).map((def) => ({
    path: `${opencodeToolDir(job.layout)}/${def.function.name}.ts`,
    content: renderOpencodeTool(def),
  }));
}
