import { describe, expect, it } from "vitest";
import { numoPullRequestFooter } from "./numo-pr-footer";

describe("numoPullRequestFooter", () => {
  it("records the model, execution environment, reasoning, and issue", () => {
    expect(
      numoPullRequestFooter({
        locale: "en",
        model: "openai/gpt-5.6",
        environment: "worktree",
        reasoningLevel: "high",
        issueIdentifier: "MIND-42",
      }),
    ).toBe(
      "🤖 Generated by Numo (minddy) · Model: `openai/gpt-5.6` · Environment: Local (isolated) · Thinking: High · Issue MIND-42",
    );
  });

  it("localizes metadata and identifies notebook work", () => {
    expect(
      numoPullRequestFooter({
        locale: "fr",
        model: "anthropic/claude-sonnet",
        environment: "cloud",
        reasoningLevel: "medium",
      }),
    ).toBe(
      "🤖 Généré par Numo (minddy) · Modèle: `anthropic/claude-sonnet` · Environnement: Cloud · Réflexion: Moyenne · Note du carnet",
    );
  });
});


it("records native thinking independently from the API reasoning compatibility value", () => {
  expect(numoPullRequestFooter({ locale: "en", model: "codex/gpt-test-codex", environment: "cloud", reasoningLevel: "medium", nativeReasoningEffort: "ultra" }))
    .toContain("Thinking: Ultra");
  expect(numoPullRequestFooter({ locale: "en", model: "codex/default", environment: "cloud", reasoningLevel: "medium", nativeReasoningEffort: null }))
    .toContain("Thinking: Automatic");
});
