import type { Locale } from "@/i18n/config";
import type { ReasoningLevel } from "@/lib/agent-reasoning";

export type NumoPrEnvironment = "cloud" | "local" | "worktree";

interface FooterCopy {
  generated: string;
  model: string;
  environment: string;
  thinking: string;
  environments: Record<NumoPrEnvironment, string>;
  reasoning: Record<ReasoningLevel, string>;
  issue: (identifier: string) => string;
  notebook: string;
}

/** Runtime-localized metadata appended to pull requests created by Numo. */
const COPY: Record<Locale, FooterCopy> = {
  en: {
    generated: "Generated by Numo (minddy)",
    model: "Model",
    environment: "Environment",
    thinking: "Thinking",
    environments: { cloud: "Cloud", local: "Local", worktree: "Local (isolated)" },
    reasoning: {
      off: "Off",
      minimal: "Minimal",
      low: "Low",
      medium: "Medium",
      high: "High",
      xhigh: "Extra high",
      max: "Maximum",
    },
    issue: (identifier) => `Issue ${identifier}`,
    notebook: "Notebook note",
  },
  fr: {
    generated: "Généré par Numo (minddy)",
    model: "Modèle",
    environment: "Environnement",
    thinking: "Réflexion",
    environments: { cloud: "Cloud", local: "Local", worktree: "Local (isolé)" },
    reasoning: {
      off: "Désactivée",
      minimal: "Minimale",
      low: "Faible",
      medium: "Moyenne",
      high: "Élevée",
      xhigh: "Très élevée",
      max: "Maximale",
    },
    issue: (identifier) => `Ticket ${identifier}`,
    notebook: "Note du carnet",
  },
  de: {
    generated: "Von Numo (minddy) erstellt",
    model: "Modell",
    environment: "Umgebung",
    thinking: "Denktiefe",
    environments: { cloud: "Cloud", local: "Lokal", worktree: "Lokal (isoliert)" },
    reasoning: {
      off: "Aus",
      minimal: "Minimal",
      low: "Niedrig",
      medium: "Mittel",
      high: "Hoch",
      xhigh: "Sehr hoch",
      max: "Maximum",
    },
    issue: (identifier) => `Ticket ${identifier}`,
    notebook: "Notizbuchnotiz",
  },
  "pt-BR": {
    generated: "Gerado pelo Numo (minddy)",
    model: "Modelo",
    environment: "Ambiente",
    thinking: "Raciocínio",
    environments: { cloud: "Nuvem", local: "Local", worktree: "Local (isolado)" },
    reasoning: {
      off: "Desativado",
      minimal: "Mínimo",
      low: "Baixo",
      medium: "Médio",
      high: "Alto",
      xhigh: "Muito alto",
      max: "Máximo",
    },
    issue: (identifier) => `Tarefa ${identifier}`,
    notebook: "Nota do caderno",
  },
  it: {
    generated: "Generato da Numo (minddy)",
    model: "Modello",
    environment: "Ambiente",
    thinking: "Ragionamento",
    environments: { cloud: "Cloud", local: "Locale", worktree: "Locale (isolato)" },
    reasoning: {
      off: "Disattivato",
      minimal: "Minimo",
      low: "Basso",
      medium: "Medio",
      high: "Alto",
      xhigh: "Molto alto",
      max: "Massimo",
    },
    issue: (identifier) => `Attività ${identifier}`,
    notebook: "Nota del taccuino",
  },
  es: {
    generated: "Generado por Numo (minddy)",
    model: "Modelo",
    environment: "Entorno",
    thinking: "Razonamiento",
    environments: { cloud: "Nube", local: "Local", worktree: "Local (aislado)" },
    reasoning: {
      off: "Desactivado",
      minimal: "Mínimo",
      low: "Bajo",
      medium: "Medio",
      high: "Alto",
      xhigh: "Muy alto",
      max: "Máximo",
    },
    issue: (identifier) => `Tarea ${identifier}`,
    notebook: "Nota del cuaderno",
  },
};

export function numoPullRequestFooter(input: {
  locale: Locale;
  model: string;
  environment: NumoPrEnvironment;
  reasoningLevel: ReasoningLevel;
  issueIdentifier?: string | null;
}): string {
  const copy = COPY[input.locale];
  return [
    `🤖 ${copy.generated}`,
    `${copy.model}: \`${input.model}\``,
    `${copy.environment}: ${copy.environments[input.environment]}`,
    `${copy.thinking}: ${copy.reasoning[input.reasoningLevel]}`,
    input.issueIdentifier ? copy.issue(input.issueIdentifier) : copy.notebook,
  ].join(" · ");
}
