import { describe, expect, it } from "vitest";

import {
  DEFAULT_SUBAGENT_FAVORITES,
  parseSubagentFavorites,
  type FavoriteSubagentModel,
} from "./subagent-favorites";
import {
  AI_MODEL_CONFIG_FIELDS,
  aiModelFallback,
  getAiConfigField,
} from "./ai-model-config";

/**
 * Sub-agent favorites can be edited from /admin: the parser is therefore
 * the CONTRACT between the screen which writes and the run which reads. What we check here,
 * is that it gives the same verdict on both sides - the API refuses when writing
 * exactly what the runtime would throw when reading (otherwise we save a
 * list which will never be used, without anyone seeing it).
 */
describe("parseSubagentFavorites", () => {
  it("rend null sur tout ce qui ne donne aucun favori utilisable", () => {
    for (const raw of [
      null,
      undefined,
      "",
      "   ",
      "{ not json",
      '"a string"',
      "{}",
      "[]",
      "[{}]",
      '[{"label":"no id"}]',
      '[{"id":"   "}]',
    ]) {
      expect(parseSubagentFavorites(raw)).toBeNull();
    }
  });

  it("garde les entrées valides et jette les autres", () => {
    const favorites = parseSubagentFavorites(
      JSON.stringify([
        { id: " ok/one ", use_case: " explore " },
        { nope: true },
        { id: "ok/two", label: "Two", thinking_effort: "off" },
        { id: "ok/three", label: "Three", thinking_effort: "high" },
      ]),
    );
    expect(favorites).toEqual([
      // Without a label, the id acts as a name; `off` is not an exposed level.
      { id: "ok/one", label: "ok/one", use_case: "explore" },
      { id: "ok/two", label: "Two", use_case: "" },
      { id: "ok/three", label: "Three", use_case: "", thinking_effort: "high" },
    ] satisfies FavoriteSubagentModel[]);
  });

  it("relit ce qu'il a produit — l'aller-retour de l'écran admin", () => {
    const json = JSON.stringify(DEFAULT_SUBAGENT_FAVORITES);
    expect(parseSubagentFavorites(json)).toEqual(DEFAULT_SUBAGENT_FAVORITES);
  });
});

describe("DEFAULT_SUBAGENT_FAVORITES", () => {
  it("est du prompt : anglais, un use-case par entrée, jamais les hints du picker", () => {
    for (const favorite of DEFAULT_SUBAGENT_FAVORITES) {
      expect(favorite.id).toMatch(/\//);
      expect(favorite.label.length).toBeGreaterThan(0);
      // The use-case IS what is used for the choice: a favorite without advice says nothing.
      expect(favorite.use_case.length).toBeGreaterThan(10);
    }
    expect(DEFAULT_SUBAGENT_FAVORITES.map((f) => f.use_case).join(" ")).not.toMatch(
      /Économique|défaut/,
    );
  });
});

/**
 * The registry is the ONLY place where a model id is hardwritten: each
 * caller reads theirs via `aiModelFallback`. A missing key or empty fallback
 * would send `undefined` to the provider — better see it here.
 */
describe("registre des réglages IA", () => {
  it("donne un défaut non vide à chaque réglage de modèle", () => {
    for (const field of AI_MODEL_CONFIG_FIELDS) {
      // A generic endpoint (or a provider without this native capability) does not have
      // no honest universal id. Its generated BYOK fields remain empty until
      // that an admin does not configure them, rather than sending a false model.
      if (field.adminLabel && field.kind === "modelId" && !field.fallback.trim()) continue;
      expect(aiModelFallback(field.key).trim().length).toBeGreaterThan(0);
    }
  });

  it("lève sur une clé inconnue plutôt que de router vers undefined", () => {
    expect(() => aiModelFallback("nope_model")).toThrow();
    expect(getAiConfigField("nope_model")).toBeUndefined();
  });

  it("sert des favoris relisibles comme défaut de la liste éditable", () => {
    const field = getAiConfigField("agent_subagent_favorites");
    expect(field?.kind).toBe("favorites");
    expect(parseSubagentFavorites(field!.fallback)).toEqual(DEFAULT_SUBAGENT_FAVORITES);
  });
});
