-- minddy — titre résumé d'une session d'agent CARNET.
--
-- Une session d'agent tire son titre de son ticket. Un run carnet (MIN-84) n'en
-- a pas : la page Agents affichait donc la note brute, tronquée sur deux lignes,
-- ce qui donne une sidebar illisible. Ce champ porte le résumé écrit au
-- lancement par le petit modèle (`app_config.conversation_title_model`, cf.
-- lib/server/assistant/title.ts), comme pour le titre d'une conversation Numo.
--
-- Nullable et sans défaut : un run d'issue n'en pose jamais (son titre est celui
-- du ticket), et un run carnet dont la génération échoue retombe sur la note.
alter table public.agent_runs add column if not exists title text;
