-- Authenticate GitLab webhook secrets without decrypting candidate mirror rows.
-- Existing rows fail closed until the owning instance sends its next secret
-- reconciliation; hook registration and rotation populate both representations.
ALTER TABLE public.forge_relay_link_mirror
  ADD COLUMN webhook_secret_digest text;

CREATE INDEX idx_forge_relay_link_mirror_gitlab_secret_digest
  ON public.forge_relay_link_mirror (webhook_secret_digest)
  WHERE provider = 'gitlab' AND webhook_secret_digest IS NOT NULL;

-- A short ledger supports both sliding-window quotas and resource leases.
-- Admission is decided in one transaction under advisory locks, so separate
-- application instances cannot overrun a quota or claim the same resource.
CREATE TABLE public.provider_operation_reservations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider text NOT NULL,
  operation text NOT NULL,
  resource_key text NOT NULL,
  lease_expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT provider_operation_provider_ck CHECK (
    provider <> '' AND length(provider) <= 64
  ),
  CONSTRAINT provider_operation_name_ck CHECK (
    operation <> '' AND length(operation) <= 64
  ),
  CONSTRAINT provider_operation_resource_ck CHECK (
    resource_key <> '' AND length(resource_key) <= 512
  )
);

CREATE INDEX idx_provider_operation_actor_window
  ON public.provider_operation_reservations (actor_id, provider, created_at DESC);
CREATE INDEX idx_provider_operation_resource_lease
  ON public.provider_operation_reservations (
    provider,
    resource_key,
    lease_expires_at DESC
  );

ALTER TABLE public.provider_operation_reservations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.provider_operation_reservations
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE public.provider_operation_reservations_id_seq
  FROM PUBLIC, anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public.reserve_provider_operation(
  p_actor_id uuid,
  p_provider text,
  p_operation text,
  p_resource_key text,
  p_limit integer,
  p_window_seconds integer,
  p_dedupe_seconds integer DEFAULT 0
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_now timestamptz := pg_catalog.clock_timestamp();
  v_count bigint;
  v_existing_lease timestamptz;
  v_oldest timestamptz;
  v_retry_after integer;
BEGIN
  IF p_actor_id IS NULL
     OR p_provider IS NULL OR p_provider = '' OR length(p_provider) > 64
     OR p_operation IS NULL OR p_operation = '' OR length(p_operation) > 64
     OR p_resource_key IS NULL OR p_resource_key = '' OR length(p_resource_key) > 512
     OR p_limit <= 0
     OR p_window_seconds <= 0 OR p_window_seconds > 86400
     OR p_dedupe_seconds < 0 OR p_dedupe_seconds > 3600 THEN
    RAISE EXCEPTION 'provider_operation_values_invalid' USING ERRCODE = '22023';
  END IF;

  -- Every actor/provider quota uses the same lock. The resource lock is
  -- independent of actor, which deduplicates checks across users and servers.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_actor_id::text || ':' || p_provider, 465)
  );
  IF p_dedupe_seconds > 0 THEN
    PERFORM pg_catalog.pg_advisory_xact_lock(
      pg_catalog.hashtextextended(
        p_provider || ':' || p_resource_key,
        466
      )
    );

    SELECT lease_expires_at
    INTO v_existing_lease
    FROM public.provider_operation_reservations
    WHERE provider = p_provider
      AND resource_key = p_resource_key
      AND lease_expires_at > v_now
    ORDER BY lease_expires_at DESC
    LIMIT 1;

    IF v_existing_lease IS NOT NULL THEN
      RETURN pg_catalog.jsonb_build_object(
        'state', 'deduplicated',
        'retry_after', GREATEST(
          1,
          CEIL(EXTRACT(EPOCH FROM (v_existing_lease - v_now)))::integer
        )
      );
    END IF;
  END IF;

  SELECT count(*), min(created_at)
  INTO v_count, v_oldest
  FROM public.provider_operation_reservations
  WHERE actor_id = p_actor_id
    AND provider = p_provider
    AND created_at >= v_now - pg_catalog.make_interval(secs => p_window_seconds);

  IF v_count >= p_limit THEN
    v_retry_after := GREATEST(
      1,
      CEIL(EXTRACT(EPOCH FROM (
        v_oldest + pg_catalog.make_interval(secs => p_window_seconds) - v_now
      )))::integer
    );
    RETURN pg_catalog.jsonb_build_object(
      'state', 'quota_exceeded',
      'retry_after', v_retry_after
    );
  END IF;

  INSERT INTO public.provider_operation_reservations (
    actor_id,
    provider,
    operation,
    resource_key,
    lease_expires_at,
    created_at
  ) VALUES (
    p_actor_id,
    p_provider,
    p_operation,
    p_resource_key,
    v_now + pg_catalog.make_interval(secs => p_dedupe_seconds),
    v_now
  );

  -- Opportunistic housekeeping keeps the ledger bounded without a cron job.
  IF pg_catalog.random() < 0.01 THEN
    DELETE FROM public.provider_operation_reservations
    WHERE created_at < v_now - interval '1 day';
  END IF;

  RETURN pg_catalog.jsonb_build_object('state', 'reserved', 'retry_after', 0);
END;
$$;

REVOKE ALL ON FUNCTION public.reserve_provider_operation(
  uuid, text, text, text, integer, integer, integer
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_provider_operation(
  uuid, text, text, text, integer, integer, integer
) TO service_role;
